#!/usr/bin/env python3
"""Banner and opening art for the website, generated by code (no downloaded images).

  python3 website/art/make_banners.py        writes website/art/out/*.jpg

Themes (one per Part):
  cmb      Parts I and II  - a synthetic Gaussian random field with a CMB-like angular power spectrum (acoustic peaks, damping
                             tail), drawn in an all-sky ellipse. Synthetic: it is not the measured sky.
  bh       Part III        - a dark horizon with a lensed, Doppler-brightened emission ring, drawn procedurally.
  lattice  Parts IV and V  - a square lattice of coupled nodes (a qubit / chip grid) with a standing wave across it.
  genome   Part VI         - the book's own genome sky: panel b of docs/book/figures/part6/fig_sky_cmb_vs_neutrophil.pdf (one
                             healthy neutrophil's pixel residual, the genome laid on the sphere).
  web      Part VII        - the four skies joined, blended left to right (Part VII's banner; also Part I's front-page card).
  chip     Part V          - a processor die from above: standard-cell rows, metal routing, memory macros.
  mosaic   Part VII's card - the four skies as a 2 x 2 mosaic, so that no two front-page cards are alike.
Each banner is 2400 x 600 px; each opening art is 1200 x 1200 px.
"""
import pathlib, subprocess, tempfile
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from PIL import Image

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent.parent
OUT = HERE / "out"
OUT.mkdir(exist_ok=True)
W, H = 2400, 600


def cmb_cl(ell):
    """A CMB-like D_ell = l(l+1)C_l/2pi shape: Sachs-Wolfe plateau, acoustic peaks near l = 220, 540, 810, Silk damping."""
    ell = np.maximum(ell, 2.0)
    plateau = 1.0
    peaks = 5.5 * np.exp(-((ell - 220) / 95) ** 2) + 2.6 * np.exp(-((ell - 540) / 120) ** 2) + 2.4 * np.exp(-((ell - 810) / 130) ** 2)
    damp = np.exp(-(ell / 1400.0) ** 2)
    return (plateau + peaks) * damp / (ell * (ell + 1))


def grf(n, seed, lmax_scale=1.0):
    """Flat-sky Gaussian random field with the CMB-like spectrum on an n x 2n grid spanning an all-sky width."""
    rng = np.random.default_rng(seed)
    ny, nx = n, 2 * n
    ky = np.fft.fftfreq(ny) * ny
    kx = np.fft.fftfreq(nx) * nx
    k = np.sqrt(ky[:, None] ** 2 + (kx[None, :] / 2.0) ** 2) * 2.0 * lmax_scale      # multipole-like index across the map
    amp = np.sqrt(cmb_cl(k * 2.2))
    amp[0, 0] = 0
    noise = rng.normal(size=(ny, nx)) + 1j * rng.normal(size=(ny, nx))
    f = np.real(np.fft.ifft2(noise * amp))
    return (f - f.mean()) / f.std()


def save(fig, name):
    fig.savefig(OUT / name, dpi=100, facecolor=fig.get_facecolor())
    plt.close(fig)
    im = Image.open(OUT / name).convert("RGB")
    im.save(OUT / name, quality=82, optimize=True)


def cmb(name, seed, size=(W, H), ellipse=True):
    w, h = size
    f = grf(512, seed)
    fig = plt.figure(figsize=(w / 100, h / 100), facecolor="#05070d")
    ax = fig.add_axes([0, 0, 1, 1]); ax.set_axis_off(); ax.set_facecolor("#05070d")
    if ellipse:
        yy, xx = np.mgrid[-1:1:f.shape[0] * 1j, -1:1:f.shape[1] * 1j]
        f = np.where(xx ** 2 + yy ** 2 <= 1, f, np.nan)
    ax.imshow(f, cmap="RdYlBu_r", vmin=-2.6, vmax=2.6, extent=[-2, 2, -1, 1], interpolation="bicubic")
    ax.set_xlim(-2.05, 2.05) if ellipse else ax.set_xlim(-2, 2)
    ax.set_ylim(-1.03, 1.03) if ellipse else ax.set_ylim(-1, 1)
    ax.set_aspect("auto")
    save(fig, name)


def blackhole(name, size=(W, H)):
    w, h = size
    y, x = np.mgrid[-1:1:h * 1j, -w / h:w / h:w * 1j]
    cx = 0.0
    r = np.hypot(x - cx, y * 1.0)
    phi = np.arctan2(y, x - cx)
    shadow = 0.32
    ring = np.exp(-((r - 0.42) / 0.035) ** 2) * (1.0 + 0.85 * np.cos(phi - np.pi))           # photon ring, Doppler-brightened side
    disk_y = y / 0.16
    disk = np.exp(-disk_y ** 2) * np.exp(-((np.abs(x - cx) - 0.75) / 0.55) ** 2) * (1.0 + 0.6 * np.sign(-(x - cx)))
    glow = 0.35 * np.exp(-((r - 0.45) / 0.25) ** 2)
    img = ring + 0.55 * disk + glow
    img[r < shadow] = 0
    rng = np.random.default_rng(3)
    stars = np.zeros_like(img)
    idx = rng.integers(0, img.size, 900)
    stars.flat[idx] = rng.uniform(0.2, 1.0, 900)
    img = img + stars * (r > 0.9)
    fig = plt.figure(figsize=(w / 100, h / 100), facecolor="#020204")
    ax = fig.add_axes([0, 0, 1, 1]); ax.set_axis_off()
    ax.imshow(np.clip(img, 0, 2.2), cmap="afmhot", vmin=0, vmax=2.0, extent=[x.min(), x.max(), -1, 1], interpolation="bilinear")
    save(fig, name)


def lattice(name, size=(W, H), seed=7):
    w, h = size
    fig = plt.figure(figsize=(w / 100, h / 100), facecolor="#060a12")
    ax = fig.add_axes([0, 0, 1, 1]); ax.set_axis_off(); ax.set_facecolor("#060a12")
    nx, ny = int(24 * w / h / 4) * 2, 12
    xs, ys = np.meshgrid(np.linspace(0, w / h, nx), np.linspace(0, 1, ny))
    wave = 0.5 + 0.5 * np.sin(2 * np.pi * (xs / (w / h) * 3.0 - ys * 0.7))
    for i in range(ny):
        ax.plot(xs[i], ys[i], color="#1f6f8b", lw=0.8, alpha=0.55)
    for j in range(nx):
        ax.plot(xs[:, j], ys[:, j], color="#1f6f8b", lw=0.8, alpha=0.55)
    ax.scatter(xs, ys, s=18 + 60 * wave, c=wave, cmap="cool", alpha=0.9, edgecolors="none")
    ax.scatter(xs, ys, s=220 * wave, c=wave, cmap="cool", alpha=0.12, edgecolors="none")
    ax.set_xlim(-0.02, w / h + 0.02); ax.set_ylim(-0.05, 1.05)
    save(fig, name)


def genome_sky():
    """The genome sky: panel b of the book's fig_sky_cmb_vs_neutrophil (one healthy neutrophil minus five others, the genome laid on
    the sphere), cut out of the rendered PDF along its all-sky ellipse."""
    pdf = REPO / "docs/book/figures/part6/fig_sky_cmb_vs_neutrophil.pdf"
    with tempfile.TemporaryDirectory() as td:
        subprocess.run(["pdftoppm", "-png", "-r", "300", "-singlefile", str(pdf), f"{td}/g"], check=True)
        im = np.asarray(Image.open(f"{td}/g.png").convert("RGB")).astype(float)
    h, w, _ = im.shape
    right = im[:, w // 2:]
    sat = right.max(axis=2) - right.min(axis=2)
    rows = np.where((sat > 40).sum(axis=1) > 0.25 * right.shape[1])[0]
    top = rows.min()
    gap = np.where(np.diff(rows) > 5)[0]
    bot = rows[gap[0]] if len(gap) else rows.max()
    cols = np.where((sat[top:bot] > 40).sum(axis=0) > 3)[0]
    crop = right[top:bot + 1, cols.min():cols.max() + 1]
    return Image.fromarray(crop.astype(np.uint8))


def genome(name, size=(W, H)):
    w, h = size
    sky = genome_sky().resize((int(w * 0.98), int(h * 0.98)), Image.LANCZOS)
    arr = np.asarray(sky).astype(float)
    hh, ww, _ = arr.shape
    yy, xx = np.mgrid[-1:1:hh * 1j, -1:1:ww * 1j]
    inside = xx ** 2 + yy ** 2 <= 0.985
    bg = np.zeros((h, w, 3)); bg[:] = (5, 7, 13)
    y0, x0 = (h - hh) // 2, (w - ww) // 2
    region = bg[y0:y0 + hh, x0:x0 + ww]
    region[inside] = arr[inside]
    Image.fromarray(bg.astype(np.uint8)).save(OUT / name, quality=82, optimize=True)


def web(name, size=(W, H)):
    w, h = size
    tiles = [OUT / "cmb_banner.jpg", OUT / "bh_banner.jpg", OUT / "lattice_banner.jpg", OUT / "genome_banner.jpg"]
    ims = [Image.open(t).convert("RGB").resize((w, h)) for t in tiles]
    out = np.zeros((h, w, 3))
    xs = np.linspace(0, 1, w)
    centres = [0.125, 0.375, 0.625, 0.875]
    weights = [np.exp(-((xs - c) / 0.14) ** 2) for c in centres]
    tot = sum(weights)
    for im, wt in zip(ims, weights):
        out += np.asarray(im, float) * (wt / tot)[None, :, None]
    Image.fromarray(out.clip(0, 255).astype(np.uint8)).save(OUT / name, quality=82, optimize=True)


def chip(name, size=(W, H), seed=11):
    """A processor die seen from above: rows of standard cells of varied width, metal routing on two layers, a few hard macros."""
    w, h = size
    rng = np.random.default_rng(seed)
    fig = plt.figure(figsize=(w / 100, h / 100), facecolor="#0b1414")
    ax = fig.add_axes([0, 0, 1, 1]); ax.set_axis_off(); ax.set_facecolor("#0b1414")
    X, Y = w / h, 1.0
    rows = 22
    for r in range(rows):
        y = 0.04 + r * (0.92 / rows)
        x = 0.03
        while x < X - 0.03:
            cw = rng.choice([0.012, 0.018, 0.026, 0.04])
            shade = rng.uniform(0.25, 0.65)
            ax.add_patch(plt.Rectangle((x, y), cw * 0.92, 0.92 / rows * 0.78, color=(0.12, 0.35 + 0.3 * shade, 0.33 + 0.2 * shade), lw=0))
            x += cw
    for _ in range(140):                       # metal-2 horizontal and metal-3 vertical routes
        if rng.random() < 0.5:
            y = rng.uniform(0.03, 0.97); x0 = rng.uniform(0, X * 0.8)
            ax.plot([x0, x0 + rng.uniform(0.1, 0.8)], [y, y], color="#d9a441", lw=0.8, alpha=0.55)
        else:
            x = rng.uniform(0.02, X - 0.02); y0 = rng.uniform(0, 0.7)
            ax.plot([x, x], [y0, y0 + rng.uniform(0.1, 0.4)], color="#e8c27a", lw=0.7, alpha=0.45)
    for _ in range(4):                         # hard macros (memories)
        mx, my = rng.uniform(0.2, X - 0.6), rng.uniform(0.15, 0.55)
        ax.add_patch(plt.Rectangle((mx, my), 0.45, 0.3, facecolor="#163236", edgecolor="#d9a441", lw=1.2))
        for k in range(1, 12):
            ax.plot([mx + 0.02, mx + 0.43], [my + k * 0.025, my + k * 0.025], color="#2f6a68", lw=0.6)
    ax.set_xlim(0, X); ax.set_ylim(0, Y)
    save(fig, name)


def mosaic(name, size=(1200, 1200)):
    """The four skies as a 2 x 2 mosaic (CMB, black hole, lattice, genome), for Part VII's card."""
    w, h = size
    tiles = ["cmb_opening.jpg", "bh_opening.jpg", "lattice_opening.jpg", "genome_opening.jpg"]
    out = Image.new("RGB", (w, h), (5, 7, 13))
    gap = 8
    tw, th = (w - gap) // 2, (h - gap) // 2
    for k, t in enumerate(tiles):
        im = Image.open(OUT / t).convert("RGB").resize((tw, th))
        out.paste(im, ((k % 2) * (tw + gap), (k // 2) * (th + gap)))
    out.save(OUT / name, quality=82, optimize=True)


def square(src_name, name):
    im = Image.open(OUT / src_name).convert("RGB")
    w, h = im.size
    im.crop(((w - h) // 2, 0, (w + h) // 2, h)).resize((1200, 1200)).save(OUT / name, quality=82, optimize=True)


if __name__ == "__main__":
    cmb("cmb_banner.jpg", seed=2026)
    cmb("cmb2_banner.jpg", seed=1965)
    blackhole("bh_banner.jpg")
    lattice("lattice_banner.jpg")
    genome("genome_banner.jpg")
    web("web_banner.jpg")
    chip("chip_banner.jpg")
    for b in ("cmb", "cmb2", "bh", "lattice", "genome", "web", "chip"):
        square(f"{b}_banner.jpg", f"{b}_opening.jpg")
    mosaic("mosaic_opening.jpg")
    print("\n".join(sorted(p.name for p in OUT.iterdir())))
