set -e; W="$(pwd)"; cd "$W/iamrepo" && git pull -q origin main 2>/dev/null || true
D=Biological_Physics/MethylPhys/hmin_calibration; E=Biological_Physics/MethylPhys/evidence_pre_atlas_2026-04
mkdir -p "$D" "$E"
cp "{{artifact:d443a69d-3092-413f-8226-3265f3cfc12d}}" "$D/g003_mcmc_framework.py"
cp "{{artifact:c6516b1e-bc2e-46d1-9537-2bbaec641ba7}}" "$D/gape_bootstrap_comparison.py"
cp "$W/gape_ev/gape_evidence/evidence_summary.json" "$E/evidence_summary.json"
cp "$W/gape_ev/gape_evidence/evidence_summary.tsv" "$E/evidence_summary.tsv"
cp "$W/gape_ev/gape_evidence/README.md" "$E/README_as_generated_2026-04-07.md"
cat > "$E/README_FIRST.md" <<'MD'
# Pre-atlas evidence database, April 2026 — published as the historical record, not as a current claim

**What this directory is.** The GAPE evidence database as it stood on **2026-04-07**, generated by the
**pre-atlas chain** (GAPE 5.0, H_min from the G-002 April posterior, marker-union surface). It is published in
full, unedited, because the validation history should be inspectable by anyone checking this work — and because
the record is the authority when the record and a later document disagree.

**What it is not.** It is **not** evidence produced by the chain commissioned in Issue 003, and none of its
numbers have been re-derived on the identity gauge. Four things a reader must know before quoting anything here:

1. **Different surface.** These A-scores were computed on the marker-union surface. The commissioned chain reads
   the **identity loci** of a class against that class's floor. The two surfaces move in *opposite directions*
   with age (RECON D2), so a number from this file and a number from Issue 003 are not comparable and must never
   be quoted side by side as if they were.
2. **Different floors.** H_min here is the G-002 April posterior. The immune floor moved from 0.795 to
   **0.838889 ± 0.0012** during calibration, when six immune cell types replaced neutrophils alone.
3. **The "detection threshold A > 1.05" in the generated README is that era's working threshold.** It is not a
   commissioned claim of this chain. Issue 003 states no detection threshold for any condition, and its
   tier breakpoints are a separate, sealed file (`tier_breakpoints.json`).
4. **Disease evidence for the commissioned chain does not exist yet.** By the author's instruction it belongs in
   **Issue 004**, after sealed runs on the commissioned chain against pre-registered bars. Nothing here
   anticipates that result.

**Two copies of `evidence_summary.json` exist and this is the complete one.** The other, generated without
network access, carries empty `gdc_availability` (`{}`), `gdc_total_cases` 0 and `geo_catalogued` 0. This copy has
them populated — 11,428 GDC cases available and 10 GEO datasets catalogued at generation time. The `results`
block is **byte-identical between the two**, so no measured value depends on which copy a reader has.

**What the summary contains**, in its own words: 28 cancer datasets, 4,304 matched tumour–normal pairs, and the
P1 comparison (A_tumour > A_normal) confirmed in 27 of 28 with a mean ΔA of 0.1589 ± 0.0721. Those are the
pre-atlas chain's figures on the pre-atlas surface, stated here so a reader knows what they are looking at.
MD
cat > "$D/README.md" <<'MD'
# H_min calibration — the MCMC that produced the floors, published for inspection

Every file here is the calibration behind the constants the chain divides by. If a reviewer wants to check
H_min, this is the directory.

| file | what it is |
|---|---|
| `gape_mcmc_g002.py` | **G-002** — the calibration that produced the eight methylation floors. emcee ensemble, 32 walkers, 5 independent chains, 500 burn-in and 5,000 production steps, SIGMA_A = 0.020, and its own reference database (`_RAW_DB`) of **37 published reference cells**, 4–6 per class, all FACS-sorted or microdissected (Roadmap/ENCODE/Lister). Every methylation chain converged with R-hat < 1.001. The immune floor moved 0.795 → **0.838889 ± 0.0012** during this calibration, when six immune cell types replaced neutrophils alone. |
| `gape_mcmc_g003b.py` | **G-003b** — the follow-on sampler. |
| `g003_mcmc_framework.py` | the framework G-003b runs on (added 2026-09-22; it had not been committed). |
| `gape_mcmc_g008.py` | **G-008**. |
| `gape_mcmc_e_a_bio.py` | the E/A_bio sampler. |
| `gape_mcmc_nbio_ordering.py` | the class **ordering** of the retired per-class n_bio (ρ = 0.905, p = 0.002). The ordering is all that was ever established; the absolute per-class values awaited a G-007 run that **was never made** (PROC-HISTORY-01), and the quantity itself is retired — superseded by the Mahaffey number M = 20.94, one number for the cell. See Issue 003 §5.0.4. |
| `gape_bootstrap_comparison.py` | the script that produced the comparison below (added 2026-09-22; the table was committed without it). |
| `bootstrap_vs_mcmc_comparison.tsv` | bootstrap against MCMC, 32 rows. |

## Read the comparison table's scope before citing it

`bootstrap_vs_mcmc_comparison.tsv` has 32 rows: **8 classes × 4 substrates — nucleosome occupancy, fuzziness,
WPS and fragment size.** **Methylation is not in it.** The title invites the opposite reading, so it is stated
plainly here: the eight methylation floors the commissioned chain actually uses were **not** cross-checked
against a bootstrap by this file. Their support is G-002's own convergence (R-hat < 1.001 on every methylation
chain) and the 37-cell reference database inside `gape_mcmc_g002.py`.

## What is not in this directory

The **raw posterior chains** are not published here — these are the scripts, the priors, the reference database
and the convergence summaries, not the samples. A reviewer who wants the chains themselves should ask; they are a
Zenodo-scale deposit rather than a repository file, and that is the honest place for them.
MD
git add -A && git -c user.name="IAMPerformance" -c user.email="iamperformance@users.noreply.github.com" commit -q -m "H_min calibration made fully inspectable, and the pre-atlas evidence database published as history rather than as a claim. Added the two files that were missing at HEAD: g003_mcmc_framework.py (the framework G-003b runs on) and gape_bootstrap_comparison.py (the script behind a table that was committed without it). hmin_calibration/README.md now names what each sampler produced - G-002's 32 walkers, 5 chains, 500+5000 steps, SIGMA_A 0.020, 37-cell _RAW_DB, R-hat < 1.001, and the immune floor moving 0.795 -> 0.838889 when six immune cell types replaced neutrophils alone - and states the scope limit a reviewer would otherwise misread: bootstrap_vs_mcmc_comparison.tsv covers nucl/fuzz/wps/frag only, 8 classes x 4 substrates, METHYLATION IS NOT IN IT. The April 2026 evidence database (28 cancer datasets, 4,304 matched pairs, 27/28 P1) is published unedited in evidence_pre_atlas_2026-04/ with a README_FIRST stating that it is the PRE-ATLAS marker-union surface with G-002 April floors, that the two surfaces move in opposite directions with age so its numbers must never be quoted beside Issue 003's, that its 'detection threshold A > 1.05' is that era's working threshold and not a commissioned claim, and that disease evidence for the commissioned chain belongs to Issue 004 after sealed runs. Of the two evidence_summary.json copies the complete one is published; the results block is byte-identical between them, so no measured value depends on the choice" && git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/hmahaffeyges/IAM-Validation.git" && git push -q origin main; git remote set-url origin https://github.com/hmahaffeyges/IAM-Validation.git; echo "pushed $(git rev-parse --short origin/main)"
cd Biological_Physics/MethylPhys/kit && python3 link_check.py 2>&1 | tail -1
cd "$W" && ls idats_gse87571 | wc -l | awk '{print "IDAT files down: "$1}'