"""Part 5 figures and tables added for TODO 9.2 (at least two figures and one table per chapter; one summary figure for the
conclusion). Every number is computed here from the chapters' own formulas or from repository files:
  docs/verification/observations/data/lvdb_dwarf_mw.csv  (Local Volume Database, Milky Way satellites)
  docs/book/figscripts/_cosmo.py                         (mu(a), linear growth, same early amplitude)
  docs/book/part2/p2_03_theory.tex                       (Section sec:numerics table of fitted alpha, beta; parsed)
  CANON/iam_canon.json                                   (Normal band 0.95-1.05)
  Biological_Physics/MethylPhys/doors/PROC_DNMT_01_PARTA_OUTCOME.md, PROC_DNMT_01_PARTB/dnmt_b_pairs.csv, PROC_TUMOUR_01_OUTCOME.md
  docs/book/main.tex and every chapter it inputs          (status labels and open problems, counted; p5_09 open-item tables, parsed)
Values typed below are only those printed in the chapter text, each with its chapter and line in a comment.
p5_01 fig_two_surfaces, tab_bh_surfaces | p5_02 fig_transit | p5_03 fig_satellite_context, tab_satellites_below
p5_04 fig_eraser_temperature, tab_eraser | p5_05 fig_mass_scaling, tab_gravdec | p5_06 fig_exponent_fit, tab_chsh
p5_07 fig_cosmo_tests | p5_08 fig_one_half, fig_cell_readings | p5_09 fig_open_items, fig_open_map
p5_10 fig_status_summary
Run: python docs/book/figscripts/fig_p5_extra.py
"""
import sys, pathlib, re, json
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import numpy as np, pandas as pd, scipy.constants as C
from scipy.integrate import solve_ivp, quad
import _bookstyle as S
import matplotlib.pyplot as plt

S.apply()
REPO, BOOK = S.REPO, S.BOOK
TAB = BOOK / "tables" / "part7"; TAB.mkdir(parents=True, exist_ok=True)
c, G, hbar, k = C.c, C.G, C.hbar, C.k
Msun, Mpc, ly, yr = 1.98847e30, 3.0857e22, 9.4607e15, 3.15576e7
CANON = json.load(open(REPO / "CANON" / "iam_canon.json"))["constants"]
NB = CANON["Normal_band"]["value"]


def sci_tex(x, d=2):
    e = int(np.floor(np.log10(abs(x)))); m = x / 10**e
    if round(m, d - 1) >= 10:
        m, e = m / 10, e + 1
    return f"${m:.{d-1}f}\\times10^{{{e}}}$"


def num(x, d=3):
    """plain for 0.01 <= |x| < 1000, else LaTeX scientific"""
    return f"{x:.{d}g}" if 0.01 <= abs(x) < 1000 else sci_tex(x, 2)


def table(path, caption, label, colspec, header, rows):
    with open(path, "w") as fh:
        fh.write("% generated by docs/book/figscripts/fig_p5_extra.py; do not edit by hand\n")
        fh.write(f"\\begin{{table}}[htbp]\\centering\\small\n\\caption{{{caption}}}\\label{{{label}}}\n")
        fh.write(f"\\begin{{tabular}}{{{colspec}}}\\toprule\n{header} \\\\\\midrule\n")
        for r in rows:
            fh.write(r if isinstance(r, str) else " & ".join(r) + " \\\\\n")
        fh.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")


# ===================== p5_01: two thermal surfaces =====================
H0 = 67.16e3 / Mpc                                 # p5_01: photon-sector H0 = 67.16
TGH = hbar * H0 / (2 * np.pi * k)
TBH = lambda M: hbar * c**3 / (8 * np.pi * G * M * k)
Nbits = lambda M: 4 * np.pi * G * M**2 / (hbar * c * np.log(2))
Gam = lambda M: c**3 / (1920 * G * M * np.log(2))   # p5_01 line 39
Meq = c**3 / (4 * G * H0)
print(f"T_GH {TGH:.3e} K; M_eq {Meq/Msun:.3e} Msun; T_BH(1 Msun) {TBH(Msun):.3e} K")
fig, (a1, a2) = plt.subplots(1, 2, figsize=(S.TEXTW, 2.6))
M = np.logspace(-1, 24, 300) * Msun
a1.plot(M / Msun, TBH(M), color=S.GR, label=r"black hole, $T_{BH}$")
a1.axhline(TGH, color=S.IAM, lw=1.2, label=f"cosmic horizon, {S.sci(TGH, 3)} K")
a1.axvline(Meq / Msun, color=S.LIGHT, lw=0.8, ls="--"); a1.axvline(7e10, color=S.DATA, lw=0.8, ls=":")
a1.text(Meq / Msun * 0.5, 1e-20, f"$M_{{\\rm eq}}$ = {S.sci(Meq/Msun, 2)}" + r" M$_\odot$", fontsize=6, ha="right")
a1.text(7e10 * 2, 1e-27, "largest known\nblack hole", fontsize=6, ha="left", color=S.DATA)
a1.set_xscale("log"); a1.set_yscale("log"); a1.set_xlabel(r"mass (M$_\odot$)"); a1.set_ylabel("temperature (K)")
a1.legend(loc="upper right", fontsize=6); a1.set_title("Hot local horizons, a cold cosmic one"); S.panel_letter(a1, "a")
Mm = np.logspace(0, 11, 100) * Msun
a2.plot(Mm / Msun, Gam(Mm), color=S.GR); a2.set_xscale("log"); a2.set_yscale("log")
a2.set_xlabel(r"mass (M$_\odot$)"); a2.set_ylabel("Hawking emission (bits s$^{-1}$)")
a2.set_title(r"$\Gamma=c^3/(1920\,GM\ln2)$"); S.panel_letter(a2, "b")
fig.tight_layout(); S.save(fig, "part7", "fig_two_surfaces")
rows = []
for m in (1, 1e3, 1e6, 1e9, 7e10, Meq / Msun):
    MM = m * Msun
    rows.append((sci_tex(m, 2) if m != 1 else "1", sci_tex(TBH(MM), 2), num(TBH(MM) / TGH, 2), sci_tex(Nbits(MM), 2), sci_tex(Gam(MM), 2)))
table(TAB / "tab_bh_surfaces.tex",
      "Black-hole horizons against the cosmic horizon today ($H_0=67.16$, $T_{GH}=" + sci_tex(TGH, 3).strip("$") + "$\\,K): temperature, "
      "ratio to $T_{GH}$, bits held $N=4\\pi GM^2/(\\hbar c\\ln2)$, and the black-body Hawking emission rate. The last row is $M_{\\rm eq}$, "
      "where the two temperatures meet. \\calc", "tab:bh_surfaces", "@{}lcccc@{}",
      "$M/M_\\odot$ & $T_{BH}$ (K) & $T_{BH}/T_{GH}$ & $N$ (bits) & $\\Gamma$ (bits\\,s$^{-1}$)", rows)

# ===================== p5_02: transit kinematics =====================
Dly = 136 * 3.26156                                  # Pleiades 136 pc (p5_02 line 52)
t = np.logspace(-1, 4, 200)                          # days
xi = Dly / (t / 365.25)
x7 = Dly / (7 / 365.25)
print(f"Pleiades {Dly:.0f} ly; xi(7 d) = {x7:.3e}")
GMe, Re, g0 = 3.986004418e14, 6.371e6, 9.80665      # IERS GM_Earth, mean radius, standard gravity
L = np.logspace(0, 3, 50); tid = 2 * GMe * L / Re**3
fig, (a1, a2) = plt.subplots(1, 2, figsize=(S.TEXTW, 2.5))
a1.plot(t, xi, color=S.GR); a1.plot(7, x7, "o", color=S.DATA, ms=4)
a1.annotate(f"7 days: ξ = {S.sci(x7, 2)}", (7, x7), xytext=(8, 2), textcoords="offset points", fontsize=6.5)
a1.axhline(1, color=S.LIGHT, lw=0.8, ls="--"); a1.text(0.12, 1.3, "ξ = 1 (light speed)", fontsize=6, color=S.GR)
a1.set_xscale("log"); a1.set_yscale("log"); a1.set_xlabel("one-way transit time to the Pleiades (days)")
a1.set_ylabel(r"required $\xi$ (rate in units of $c$)"); a1.set_title(f"{Dly:.0f} ly in a given time"); S.panel_letter(a1, "a")
a2.plot(L, tid / g0, color=S.GR); a2.set_xscale("log"); a2.set_yscale("log")
for LL in (10, 100):
    v = 2 * GMe * LL / Re**3 / g0; a2.plot(LL, v, "o", color=S.DATA, ms=3.5)
    a2.annotate(f"{LL} m: {S.sci(v, 2)} g", (LL, v), xytext=(6, -8), textcoords="offset points", fontsize=6)
a2.set_xlabel("length of the body $L$ (m)"); a2.set_ylabel(r"tidal residual $2GML/r^3$ in units of $g$")
a2.set_title("What a body in free fall feels at Earth's surface"); S.panel_letter(a2, "b")
fig.tight_layout(); S.save(fig, "part7", "fig_transit")

# ===================== p5_03: satellites =====================
sat = pd.read_csv(REPO / "docs/verification/observations/data/lvdb_dwarf_mw.csv")
meas = sat[sat.vlos_sigma.notna()].copy(); ul = sat[sat.vlos_sigma.isna() & sat.vlos_sigma_ul.notna()].copy()
n_any = len(meas) + len(ul)
below = pd.concat([meas[meas.vlos_sigma < 4].assign(sig=meas.vlos_sigma, lim=False),
                   ul[ul.vlos_sigma_ul < 4].assign(sig=ul.vlos_sigma_ul, lim=True)]).sort_values("sig")
print(f"below-floor d_GC range {below.distance_gc.min():.0f}-{below.distance_gc.max():.0f} kpc"); print(f"satellites {len(sat)}; with dispersion or limit {n_any}; measured {len(meas)}; limits {len(ul)}; below 4 km/s {len(below)}")
assert (len(sat), n_any, len(below)) == (68, 54, 25)
fig, (a1, a2) = plt.subplots(1, 2, figsize=(S.TEXTW, 2.6), sharey=True)
for a, col, xl in ((a1, "distance_gc", "Galactocentric distance (kpc)"), (a2, "mass_stellar", r"stellar mass, $\log_{10}(M_*/M_\odot)$")):
    a.errorbar(meas[col], meas.vlos_sigma, yerr=[meas.vlos_sigma_em, meas.vlos_sigma_ep], fmt="o", ms=3, color=S.IAM, elinewidth=0.5, lw=0)
    a.plot(ul[col], ul.vlos_sigma_ul, "v", ms=4, color=S.SKY)
    a.axhline(4, color=S.DATA, lw=0.9, ls="--"); a.set_xlabel(xl); a.set_yscale("log")
a1.set_xscale("log"); a1.set_ylabel(r"velocity dispersion $\sigma_v$ (km s$^{-1}$)")
a1.text(380, 0.6, "dashed: proposed floor, 4 km s$^{-1}$", fontsize=6, color=S.DATA, ha="right")
from matplotlib.ticker import NullFormatter
a1.xaxis.set_minor_formatter(NullFormatter())
s2 = sat[sat.name == "Segue 2"].iloc[0]
a1.annotate("Segue 2", (s2.distance_gc, s2.vlos_sigma_ul), xytext=(-30, -10), textcoords="offset points", fontsize=6)
a1.set_title("Dispersion against Galactocentric distance"); a2.set_title("Dispersion against stellar mass")
S.panel_letter(a1, "a"); S.panel_letter(a2, "b", dx=-0.06)
fig.tight_layout(); S.save(fig, "part7", "fig_satellite_context")
br = [(r["name"], (f"$<{r.sig:.2f}$" if r.lim else f"{r.sig:.2f}"), f"{r.distance_gc:.0f}") for _, r in below.iterrows()]
half = (len(br) + 1) // 2
rows = [(*br[i], *(br[i + half] if i + half < len(br) else ("", "", ""))) for i in range(half)]
table(TAB / "tab_satellites_below.tex",
      f"The {len(below)} Milky Way satellites (of {n_any} with a measured dispersion or an upper limit) whose line-of-sight velocity "
      "dispersion lies below 4~km\\,s$^{-1}$, from the Local Volume Database~\\cite{Pace2025LVDB}; $<$ marks an upper limit. $d_{\\rm GC}$ is "
      "the Galactocentric distance. \\observed", "tab:satellites_below", "@{}lrr@{\\hspace{2em}}lrr@{}",
      "satellite & $\\sigma_v$ (km\\,s$^{-1}$) & $d_{\\rm GC}$ (kpc) & satellite & $\\sigma_v$ (km\\,s$^{-1}$) & $d_{\\rm GC}$ (kpc)", rows)

# ===================== p5_04: erasure fidelity and detector temperature =====================
QL = lambda T: k * T * np.log(2) / C.e               # eV
F = lambda Q, T: 1 - np.exp(-QL(T) / Q)
Ts = (300.0, 77.0, 4.2, 0.010)
fig, (a1, a2) = plt.subplots(1, 2, figsize=(S.TEXTW, 2.5))
Q = np.logspace(-9, 1, 300)
for T_, col in zip(Ts, (S.DATA, S.GOLD, S.IAM, S.GR)):
    a1.plot(Q, F(Q, T_), color=col, label=f"$T_D$ = {T_:g} K")
a1.axvline(0.1, color=S.LIGHT, lw=0.8, ls="--"); a1.set_xscale("log"); a1.set_xlabel("dissipated energy $Q$ (eV)")
a1.set_ylabel("erasure fidelity $F$"); a1.legend(loc="upper right", fontsize=6); a1.set_title("$F=1-e^{-Q_L/Q}$ shifts with $T_D$")
S.panel_letter(a1, "a")
TT = np.logspace(-3, 3, 200); a2.plot(TT, F(0.1, TT), color=S.GR)
for T_ in (0.010, 4.0, 300.0):
    v = F(0.1, T_); a2.plot(T_, v, "o", color=S.DATA, ms=3.5)
    a2.annotate(f"{T_:g} K: {v:.3f}", (T_, v), xytext=(-20 if T_ < 1 else -48, 8), textcoords="offset points", fontsize=6)
    print(f"F(Q=0.1 eV, T={T_} K) = {v:.4f}")
a2.set_xscale("log"); a2.set_xlabel("detector temperature $T_D$ (K)"); a2.set_ylabel("$F$ at $Q=0.1$ eV")
a2.set_title("One marker, three temperatures"); S.panel_letter(a2, "b")
fig.tight_layout(); S.save(fig, "part4", "fig_eraser_temperature")
rows = [(f"$Q_L$ at {T_:g}~K", f"{num(QL(T_))}~eV", "", "") for T_ in Ts] + ["\\midrule\n"]
for nm, Qv in (("CCD pixel", 3.0), ("retinal rod", 2.5), ("crossover $Q=Q_L$", QL(300)), ("reversible marker, $Q/Q_L=0.04$", 0.04 * QL(300))):
    r = Qv / QL(300); rows.append((nm, f"{num(Qv)}~eV", f"{r:.3g}", f"{F(Qv, 300):.3g}" if F(Qv, 300) < 0.999 else f"$1-{sci_tex(np.exp(-1/r),2).strip('$')}$"))
table(BOOK / "tables" / "part4" / "tab_eraser.tex",
      "Top: the threshold $Q_L=k_BT_D\\ln2$ at four detector temperatures. Bottom: the chapter's examples at 300~K, with $Q/Q_L$ and the "
      "erasure fidelity of Eq.~\\eqref{eq:F}. The criterion is \\conjecture; the fidelity form is assumed.", "tab:eraser", "@{}lccc@{}",
      "case & $Q$ & $Q/Q_L$ & $F$", rows)

# ===================== p5_05: gravitational decoherence, mass scaling =====================
rho = 2200.0                                          # silica (p5_05 line 68)
R = lambda m: (3 * m / (4 * np.pi * rho)) ** (1 / 3)
EG = lambda m, r=None: G * m**2 / (R(m) if r is None else r)
tIAM = lambda E, T: hbar * k**2 * T**2 * np.log(2) / E**3
tDP = lambda E: hbar / E
m = np.logspace(-18, -9, 300)
fig, ax = plt.subplots(figsize=(0.62 * S.TEXTW, 2.8))
ax.plot(m, tDP(EG(m)), color=S.GR, lw=1.4, label=r"Diósi–Penrose $\hbar/E_G$ ($\propto m^{-5/3}$)")
cross = {}
for T_, ls in ((0.010, "-"), (0.020, "--"), (0.040, ":")):
    ax.plot(m, tIAM(EG(m), T_), color=S.IAM, ls=ls, label=f"IAM, {T_*1e3:.0f} mK ($\\propto m^{{-5}}$)")
    lm = np.log(m); d = np.log(tIAM(EG(m), T_)) - np.log(tDP(EG(m)))
    cross[T_] = np.exp(np.interp(0, d[::-1], lm[::-1]))
    ax.plot(cross[T_], tDP(EG(cross[T_])), "o", color=S.IAM, ms=3)
    print(f"crossover at {T_*1e3:.0f} mK: m = {cross[T_]:.3e} kg, tau = {tDP(EG(cross[T_])):.3e} s")
ax.plot(1e-12, tIAM(EG(1e-12), 0.01), "s", color=S.DATA, ms=4); ax.plot(1e-12, tDP(EG(1e-12)), "s", color=S.DATA, ms=4)
ax.set_xscale("log"); ax.set_yscale("log"); ax.set_ylim(1e-12, 1e25); ax.set_xlabel("mass of a silica sphere (kg)")
ax.set_ylabel("coherence time (s)"); ax.legend(loc="upper right", fontsize=5.8); ax.set_title("Two laws, two mass exponents")
fig.tight_layout(); S.save(fig, "part7", "fig_mass_scaling")
rows = []
Ecat = 7.1e-9                                         # p5_05 line 61
rows.append(("4~kg (the cat)", "0.15~m (implied)", sci_tex(Ecat, 2), "300~K", sci_tex(tIAM(Ecat, 300), 2), sci_tex(tDP(Ecat), 2)))
for T_ in (0.010, 0.020, 0.040):
    E = EG(1e-12); rows.append(("$10^{-12}$~kg silica", f"{R(1e-12)*1e6:.2f}~$\\mu$m", sci_tex(E, 2), f"{T_*1e3:.0f}~mK", f"{num(tIAM(E, T_))}~s", f"{tDP(E)*1e6:.2g}~$\\mu$s"))
for T_ in (0.010,):
    mc = cross[T_]; E = EG(mc)
    rows.append(("equal times, silica", f"{R(mc)*1e6:.2f}~$\\mu$m", sci_tex(E, 2), f"{T_*1e3:.0f}~mK", sci_tex(tIAM(E, T_), 2) + "~s", sci_tex(tDP(E), 2) + "~s"))
print(f"cat tau_IAM {tIAM(Ecat,300):.3e} s; sphere E_G {EG(1e-12):.3e}, tau_IAM(10 mK) {tIAM(EG(1e-12),0.01):.1f} s, tau_DP {tDP(EG(1e-12)):.2e} s")
table(TAB / "tab_gravdec.tex",
      "Eq.~\\eqref{eq:tauIAM} against $\\tau_{\\rm DP}=\\hbar/E_G$, $E_G=Gm^2/R$, for the chapter's cases. The last row is the silica sphere at "
      f"which the two times are equal at 10~mK ($m=" + sci_tex(cross[0.010], 2).strip("$") + "$~kg); below it the IAM time is the longer. "
      "The rate behind $\\tau_{\\rm IAM}$ is \\conjecture; the numbers are \\calc.", "tab:gravdec", "@{}llcccc@{}",
      "body & $R$ & $E_G$ (J) & $T$ & $\\tau_{\\rm IAM}$ & $\\tau_{\\rm DP}$", rows)

# ===================== p5_06: exponent fit; CHSH table =====================
p203 = (BOOK / "part2" / "p2_03_theory.tex").read_text()
fits = {float(eval(n)): (float(a), float(b)) for n, a, b in re.findall(r"\$D\^\{?([\d./]+)\}?(?:\\,)?\\Omega_m(?:\(a\))?(?:\\,)?f(?:/T_H)?\$ & ([\d.]+) & ([\d.]+)", p203)}
fits = {(2.5 if n == 5 / 2 else n): v for n, v in fits.items()}
print("parsed fits", fits)
assert 2.5 in fits and 3.5 in fits
fig, (a1, a2) = plt.subplots(1, 2, figsize=(S.TEXTW, 2.5))
ns = sorted(fits)
a1.plot(ns, [fits[n][0] for n in ns], "o-", color=S.IAM, ms=4, label=r"$\alpha$")
a1.plot(ns, [fits[n][1] for n in ns], "s--", color=S.ALT, ms=4, label=r"$\beta$")
a1.axhline(1, color=S.GR, lw=0.8); a1.axvline(2.5, color=S.LIGHT, lw=0.8, ls=":"); a1.axvline(3.5, color=S.LIGHT, lw=0.8, ls=":")
a1.text(2.53, 1.13, "5/2", fontsize=6); a1.text(3.53, 1.13, "7/2", fontsize=6)
a1.set_xlabel(r"exponent $n$ of $D^n\Omega_m f/T_H$"); a1.set_ylabel(r"fitted $\exp(\alpha-\beta/a)$")
a1.legend(loc="lower right", fontsize=6.5); a1.set_title("The cosmology wants $n\\approx3$–$4$"); S.panel_letter(a1, "a")
a = np.linspace(0.15, 1.0, 200)
a2.plot(a, np.exp(1 - 1 / a), color=S.GR, lw=1.6, label=r"$E(a)=e^{1-1/a}$")
for n, col, ls in ((2.5, S.DATA, "--"), (3.5, S.IAM, ":")):
    al, be = fits[n]; a2.plot(a, np.exp(al - be / a), color=col, ls=ls, label=f"$n$ = {n:g}: $e^{{{al}-{be}/a}}$")
a2.set_yscale("log"); a2.set_xlabel("scale factor $a$"); a2.set_ylabel("accumulated record, normalised")
a2.legend(loc="lower right", fontsize=6); a2.set_title("5/2 does not reproduce the activation"); S.panel_letter(a2, "b")
fig.tight_layout(); S.save(fig, "part4", "fig_exponent_fit")
rows = []
cstar = np.sqrt(2) - 1; tstar = 1 / np.log(1 / (1 - cstar))
for x in sorted((0.5, 1.0, 1.5, tstar, 2.0, 3.0, 5.0, 10.0)):
    D = np.exp(-1 / x); cc = 1 - D
    rows.append((f"{x:.2f}", f"{D:.3f}", f"{cc:.3f}", f"{2*np.sqrt(1+cc**2):.3f}", f"{np.sqrt(2)*(1+cc):.3f}"))
print(f"S_fixed = 2 at c = {cstar:.4f}, t/tau = {tstar:.3f}")
table(BOOK / "tables" / "part4" / "tab_chsh.tex",
      "CHSH values for an entangled massive pair under pointer-basis dephasing with the assumed ramp, $D=E_q(t/\\tau_{\\rm IAM})/e="
      "e^{-\\tau_{\\rm IAM}/t}$, $c=1-D$: the largest value $2\\sqrt{1+c^2}$ \\derived, and the value at the settings optimal for the "
      "undecohered pair, $\\sqrt2(1+c)$, which reaches 2 at $t/\\tau_{\\rm IAM}=" + f"{tstar:.2f}" + "$. Entangled photons stay at $2\\sqrt2=2.828$. "
      "The ramp is \\conjecture.", "tab:chsh", "@{}ccccc@{}",
      "$t/\\tau_{\\rm IAM}$ & $D$ & $c$ & $S_{\\max}$ & $S$, fixed settings", rows)

# ===================== p5_07: cosmological tests =====================
import _cosmo as K
mu0 = K.mu(1.0) - 1
zz = np.linspace(0.0, 2.0, 81); aa = 1 / (1 + zz)
EGx = 100 * (K.f(K.LCDM, aa) / K.f(K.IAM, aa) - 1)
Dd = K.amp_deficit(zz)
print(f"mu0 {mu0:.4f}; E_G excess z=0.3 {np.interp(0.3, zz, EGx):.2f} %, z=0.5 {np.interp(0.5, zz, EGx):.2f} %; D deficit z=0 {Dd[0]:.2f} %")
fig, (a1, a2) = plt.subplots(1, 2, figsize=(S.TEXTW, 2.6))
x = np.linspace(-0.5, 0.4, 600)
# Present free-mu0 constraints only; the survey forecast with the IAM mu(z) is fig_p2_euclid_forecast.py (p2_16, Section sec:sp_euclid).
a1.axvline(mu0, color=S.IAM, lw=1.4, label=f"IAM $\\mu_0$ = {mu0:.3f}")
for i, (v, lo, hi, lab) in enumerate(((0.064, 0.151, 0.099, "Planck + RSD"), (0.11, 0.54, 0.45, "DESI full shape"))):   # p5_07, measured: Planck + RSD median and central 68 % (chain planck_rsd_mu0_float: -0.087 to +0.163); DESI 68 %
    y = 0.45 + 0.4 * i; a1.errorbar(v, y, xerr=[[lo], [hi]], fmt="o", ms=3, color=S.DATA, elinewidth=0.8, capsize=2)
    a1.text(v, y + 0.05, lab + " (measured)", fontsize=6, va="bottom", ha="center", color=S.DATA)
a1.axvline(0, color=S.GR, lw=0.8)
a1.text(0.015, 1.25, "GR", fontsize=6); a1.set_xlim(-0.8, 0.8); a1.set_ylim(0, 1.4)
a1.set_xlabel(r"$\mu_0$"); a1.set_yticks([]); a1.spines["left"].set_visible(False)
a1.legend(loc="lower left", bbox_to_anchor=(0.0, 0.0), fontsize=5.6, handlelength=1.4, frameon=True, framealpha=0.9, edgecolor="none"); a1.set_title(f"$\\mu_0$ = {mu0:.3f} against present constraints"); S.panel_letter(a1, "a", dx=-0.02)
a2.plot(zz, EGx, color=S.IAM, label=r"$E_G$ above $\Lambda$CDM")
a2.plot(zz, Dd, color=S.ALT, ls="--", label=r"growth factor $D$ below $\Lambda$CDM")
a2.axhline(0, color=S.GR, lw=0.8)
for z0 in (0.3, 0.5):
    v = np.interp(z0, zz, EGx); a2.plot(z0, v, "o", color=S.IAM, ms=3.5)
    a2.annotate(f"+{v:.1f} %", (z0, v), xytext=(4, 4), textcoords="offset points", fontsize=6)
a2.plot(0, Dd[0], "s", color=S.ALT, ms=3.5); a2.annotate(f"{Dd[0]:.2f} %", (0, Dd[0]), xytext=(5, -9), textcoords="offset points", fontsize=6)
a2.set_xlabel("redshift $z$"); a2.set_ylabel("difference from $\\Lambda$CDM (%)"); a2.legend(loc="upper right", fontsize=6)
a2.set_title(r"Growth falls, lensing ($\Sigma=1$) does not"); S.panel_letter(a2, "b")
fig.tight_layout(); S.save(fig, "part7", "fig_cosmo_tests")

# ===================== p5_08: the half that recurs =====================
fig, ax = plt.subplots(1, 3, figsize=(S.TEXTW, 2.3))
Rs = np.logspace(-2, 2, 9); frac = []
for Rr in Rs:                                          # C = 1, V = 1: E_supply = C V^2, E_R = int I^2 R dt
    Er = quad(lambda tt: (np.exp(-tt / Rr) / Rr) ** 2 * Rr, 0, 60 * Rr)[0]; frac.append(Er / 1.0)
ax[0].plot(Rs, frac, "o-", color=S.IAM, ms=3); ax[0].set_xscale("log"); ax[0].set_ylim(0, 1)
ax[0].set_xlabel(r"resistance $R$ ($\Omega$, $C$ = 1 F)"); ax[0].set_ylabel("dissipated / drawn from supply")
ax[0].set_title("charging a gate", fontsize=7)
Mm = np.logspace(-8, 11, 40) * Msun
ratio = Nbits(Mm) * k * TBH(Mm) * np.log(2) / (Mm * c**2)
ax[1].plot(Mm / Msun, ratio, color=S.GR); ax[1].set_xscale("log"); ax[1].set_ylim(0, 1)
ax[1].set_xlabel(r"mass (M$_\odot$)"); ax[1].set_ylabel(r"$N k_BT_H\ln2/Mc^2$"); ax[1].set_title("a horizon's bits (Smarr)", fontsize=7)
es = np.linspace(0, 0.9, 10); vr = []
for e in es:                                           # GM = 1, a = 1: integrate one period, time-average K and U
    r0 = 1 - e; v0 = np.sqrt((1 + e) / (1 - e))
    sol = solve_ivp(lambda tt, y: [y[2], y[3], -y[0] / np.hypot(y[0], y[1])**3, -y[1] / np.hypot(y[0], y[1])**3],
                    (0, 2 * np.pi), [r0, 0, 0, v0], rtol=1e-11, atol=1e-12, dense_output=True)
    tt = np.linspace(0, 2 * np.pi, 20001); y = sol.sol(tt)
    Kk = 0.5 * (y[2]**2 + y[3]**2); U = -1 / np.hypot(y[0], y[1])
    vr.append(np.trapezoid(Kk, tt) / abs(np.trapezoid(U, tt)))
ax[2].plot(es, vr, "o-", color=S.ALT, ms=3); ax[2].set_ylim(0, 1)
ax[2].set_xlabel("orbital eccentricity"); ax[2].set_ylabel(r"$\langle K\rangle/|\langle U\rangle|$"); ax[2].set_title("a Kepler orbit (virial)", fontsize=7)
print(f"RC fraction {min(frac):.6f}-{max(frac):.6f}; Smarr {ratio.min():.6f}-{ratio.max():.6f}; virial {min(vr):.5f}-{max(vr):.5f}")
for i, a in enumerate(ax):
    a.axhline(0.5, color=S.LIGHT, lw=0.8, ls="--", zorder=0); S.panel_letter(a, "abc"[i], dx=-0.28)
fig.tight_layout(w_pad=0.8); S.save(fig, "part7", "fig_one_half")

# p5_08 cell-readings figure retired 2026-10-04 (development readings; author ruling)


# ===================== book-wide parsing: status labels, open problems, p5_09 items =====================
main = (BOOK / "main.tex").read_text()
# Part numbers follow the printed \\part{} headings in main.tex (seven parts), not the source folder names;
# front matter before Part I is 0 and appendices after \\appendix are left out.
order, part, file_part = [], 0, {}
for line in main.splitlines():
    if line.strip().startswith("%"):
        continue
    if re.match(r"\s*\\part\{", line):
        part += 1
    if re.match(r"\s*\\appendix", line):
        break
    m_ = re.search(r"\\input\{(part\d/[^}]+)\}", line)
    if m_:
        order.append(m_.group(1)); file_part[m_.group(1)] = part
NPART = part
ROMAN = {1: "I", 2: "II", 3: "III", 4: "IV", 5: "V", 6: "VI", 7: "VII", 8: "VIII"}
txt = {f: "\n".join(l for l in (BOOK / f"{f}.tex").read_text().splitlines() if not l.lstrip().startswith("%")) for f in order}
labels = {}
for f, t_ in txt.items():
    for lab in re.findall(r"\\label\{(ch:[^}]+)\}", t_):
        labels[lab] = f
MAC = ["derived", "calc", "calibrated", "measured", "observed", "fitted", "conjecture", "analogy", "prediction", "openprob", "interp"]
NAMES = {"derived": "derived", "calc": "calculated", "calibrated": "calibrated", "measured": "measured", "observed": "observed",
         "fitted": "fitted", "conjecture": "conjecture", "analogy": "analogy", "prediction": "prediction", "openprob": "open problem",
         "interp": "interpretation"}
cnt = {p: {mm: 0 for mm in MAC} for p in range(0, NPART + 1)}
for f, t_ in txt.items():
    for mm in MAC:
        cnt[file_part[f]][mm] += len(re.findall(r"\\" + mm + r"(?![A-Za-z])", t_))

# p5_09 open items
p509 = txt["part7/p7_09_open"]
groups = {}
for sec, body in re.findall(r"\\section\{([^}]*)\}\s*\{\\small\\begin\{longtable\}(.*?)\\end\{longtable\}", p509, re.S):
    items = []
    for row in re.split(r"\\\\\s*\n", body.split("\\endhead", 1)[1]):
        mm = re.search(r"\\textbf\{([A-Z]\d+)\.", row)
        if not mm:
            continue
        who = row.split("&")[-1].strip()
        refs = re.findall(r"\\ref\{(ch:[^}]+)\}", row)
        items.append((mm.group(1), who, refs))
    groups[sec] = items
print({s_: len(v) for s_, v in groups.items()})
WHO = ["we", "we, data needed", "we, data due", "we, experiment", "data needed", "data due", "experiment"]
fig, (a1, a2) = plt.subplots(1, 2, figsize=(S.TEXTW, 2.9))
cols = [S.IAM, S.SKY, S.GR, S.ALT2, S.GOLD, S.ALT, S.DATA]
left = np.zeros(len(groups))
for w, col in zip(WHO, cols):
    v = np.array([sum(1 for it in items if it[1] == w) for items in groups.values()])
    if v.sum():
        a1.barh(range(len(groups)), v, left=left, color=col, height=0.55, label=w); left += v
other = [it for items in groups.values() for it in items if it[1] not in WHO]
assert not other, other
a1.set_yticks(range(len(groups))); a1.set_yticklabels(list(groups)); a1.invert_yaxis()
a1.set_xlabel("open items"); a1.set_xlim(0, 21); a1.legend(loc="upper center", bbox_to_anchor=(0.45, -0.32), ncol=3, fontsize=5.8, frameon=False); a1.set_title("Who can settle each item"); S.panel_letter(a1, "a", dx=-0.32)
origin = {p: 0 for p in range(1, NPART + 1)}
for items in groups.values():
    for it in items:
        for p in {file_part[labels[r]] for r in it[2] if r in labels and file_part[labels[r]] >= 1}:
            origin[p] += 1
a2.bar(list(origin), list(origin.values()), color=S.IAM, width=0.6)
for p, v in origin.items():
    a2.text(p, v + 0.2, str(v), ha="center", fontsize=6)
a2.set_xticks(list(origin)); a2.set_xticklabels([ROMAN[p] for p in origin], fontsize=6.5); a2.set_xlabel("part of the book"); a2.set_ylabel("items citing a chapter there")
a2.set_title("Where the open items arise"); S.panel_letter(a2, "b", dx=-0.16)
fig.tight_layout(); S.save(fig, "part7", "fig_open_items")
print("origin by part", origin)

# open problems per chapter, book-wide
fig, ax = plt.subplots(figsize=(S.TEXTW, 2.6))
op = [(f, len(re.findall(r"\\openprob(?![A-Za-z])", txt[f]))) for f in order if file_part[f] >= 1]
colp = dict(zip(range(1, NPART + 1), [S.GR, S.IAM, S.SKY, S.GOLD, S.ALT, S.DATA, S.ALT2, S.IAM]))
ax.bar(range(len(op)), [v for _, v in op], color=[colp[file_part[f]] for f, _ in op], width=0.8)
starts = {}
for i, (f, _) in enumerate(op):
    starts.setdefault(file_part[f], i)
for p, i0 in starts.items():
    ax.axvline(i0 - 0.5, color="0.85", lw=0.6, zorder=0)
    ax.text(i0, max(v for _, v in op) * (1.06 if p % 2 else 0.95), f"Part {ROMAN[p]}", fontsize=6.5, color=colp[p])
ax.set_ylim(0, max(v for _, v in op) * 1.2); ax.set_xticks([]); ax.set_xlabel("chapters in book order"); ax.set_ylabel(r"open problems labelled")
ax.set_title(f"{sum(v for _, v in op)} open-problem labels across {len(op)} chapters")
fig.tight_layout(); S.save(fig, "part7", "fig_open_map")

# p5_10: the status summary of the whole book
fig, ax = plt.subplots(figsize=(S.TEXTW, 3.1))
parts = list(range(1, NPART + 1))
pal = {"derived": "#0072B2", "calc": "#56B4E9", "calibrated": "#E69F00", "fitted": "#F0C060", "measured": "#D55E00",
       "observed": "#E8956A", "prediction": "#009E73", "conjecture": "#CC79A7", "analogy": "#E3B5D2", "interp": "#999999",
       "openprob": "#4D4D4D"}
seq = ["derived", "calc", "measured", "observed", "calibrated", "fitted", "prediction", "conjecture", "analogy", "interp", "openprob"]
left = np.zeros(len(parts))
for mm in seq:
    v = np.array([cnt[p][mm] for p in parts], float)
    ax.barh(range(len(parts)), v, left=left, color=pal[mm], height=0.6, label=NAMES[mm]); left += v
for i, p in enumerate(parts):
    ax.text(left[i] + 3, i, str(int(left[i])), va="center", fontsize=6)
ax.set_yticks(range(len(parts))); ax.set_yticklabels([f"Part {ROMAN[p]}" for p in parts]); ax.invert_yaxis()
ax.set_xlabel("status labels in the text"); ax.legend(ncol=6, fontsize=5.8, loc="upper center", bbox_to_anchor=(0.5, -0.25))
ax.set_title("What the book claims, and with what standing")
fig.tight_layout(); S.save(fig, "part7", "fig_status_summary")
json.dump({str(p): cnt[p] for p in cnt}, open(BOOK / "figures" / "part7" / "status_counts.json", "w"), indent=1)
print("status counts", {p: sum(cnt[p].values()) for p in cnt})
