"""Part 3 figures and tables added for TODO 9.2 (at least two figures and one table per chapter).
Every number is computed here from physical constants (scipy.constants) or from repository files:
  CANON/iam_canon.json                                  (E_hold_meth = 3.41 kT, P_neutrophil_IAM_A = 1.099)
  Hughes et al. arXiv:2510.17286 and Ransford et al. arXiv:2511.05465 (abstract values, typed with the sentence quoted)
  Jin et al. PRL 114, 240501 (2015) (transmon effective temperature 35 mK); Google Quantum AI, Nature 638, 920 (2025) (mean T1 = 68 us)
  Biological_Physics/MethylPhys/doors/PROC_TUMOUR_01_OUTCOME.md (per-patient copy errors, parsed)
  Biological_Physics/MethylPhys/doors/PROC_DNMT_01_PARTB/dnmt_b_pairs.csv (per-library copy errors)
Values typed below are only those printed in the chapter text (Delta_Al = 182 ueV of p3_01; the transmon worked reading of p3_03), each
with its chapter in a comment.
p3_01 tab_T1_xqp       : T1^qp from Catelani's rate (Eq. eq:catelani) at 4 and 5 GHz, and the simpler x_qp*omega estimate.
p3_03 fig_qubit_gauge  : the qubit gauge, each device against itself: thermal floor p_eq t_g/T1 (transmon reading), as built at 1,
                         threshold at 1e-2/eps; ion devices with a primary published error; eps vs p.
p3_06 tab_chip_scales  : the scales at a CMOS gate and the Landauer floor at 40, 75 and 105 C.
p3_07 fig_four_floors  : the four floors in their own variables; fig_cell_gauge: IAM-A = H(eps)/(P H(eps0)).
p3_09 fig_reach_cell   : reference vs changed copy error.
Run: python docs/book/figscripts/fig_p3_extra.py
"""
import sys, pathlib, re, json, importlib.util
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import numpy as np, pandas as pd, scipy.constants as C
import _bookstyle as S
import matplotlib.pyplot as plt

S.apply()
REPO, BOOK = S.REPO, S.BOOK
TAB = BOOK / "tables" / "part3"; TAB.mkdir(parents=True, exist_ok=True)


CANON = json.load(open(REPO / "CANON" / "iam_canon.json"))["constants"]
EH, P = CANON["E_hold_meth"]["value"], CANON["P_neutrophil_IAM_A"]["value"]
H2 = lambda x: -(x * np.log2(x) + (1 - x) * np.log2(1 - x))


def texsci(s):
    """'$8.4\\times10^{-5}$' -> 8.4e-5"""
    s = s.replace("$", "").replace(" ", "")
    m = re.match(r"([\d.]+)\\times10\^\{?(-?\d+)\}?", s)
    return float(m.group(1)) * 10 ** int(m.group(2))


def sci_tex(x, d=2):
    e = int(np.floor(np.log10(abs(x)))); m = x / 10**e
    return f"${m:.{d-1}f}\\times10^{{{e}}}$"


# ============ p3_01 table: T1^qp against x_qp ============
Delta = 182e-6 * C.e        # Delta_Al, p3_01 line 47
rows = []
for x in (1e-8, 2.4e-8, 1e-7, 1e-6, 1e-5):
    t = []
    for fq in (4e9, 5e9):
        w = 2 * np.pi * fq
        t.append(1 / (x * w / np.pi * np.sqrt(2 * Delta / (C.hbar * w))))
    t.append(1 / (x * 2 * np.pi * 5e9))
    rows.append((x, *t))
    print(f"x_qp {x:.1e}: T1 Catelani 4 GHz {t[0]*1e3:.3g} ms, 5 GHz {t[1]*1e3:.3g} ms, x*omega 5 GHz {t[2]*1e3:.3g} ms")
fmt = lambda s: f"{s*1e3:.3g}"
with open(TAB / "tab_T1_xqp.tex", "w") as fh:
    fh.write("% generated by docs/book/figscripts/fig_p3_extra.py; do not edit by hand\n")
    fh.write("\\begin{table}[htbp]\\centering\\small\n\\caption{Quasiparticle-limited $T_1$ of an Al transmon "
             "($\\Delta_{\\rm Al}=182\\,\\mu$eV) from Eq.~\\eqref{eq:catelani} at two qubit frequencies, and the simpler estimate "
             "$\\Gamma_1^{\\rm qp}\\approx\\xqp\\,\\omega_q$ at 5~GHz. The first two rows bracket the 1~ms target; the range "
             "$10^{-8}$--$10^{-6}$ is the measured background of best-isolated devices~\\cite{Riste2013}. \\calc}\\label{tab:T1xqp}\n")
    fh.write("\\begin{tabular}{@{}lccc@{}}\\toprule\n$\\xqp$ & $T_1^{\\rm qp}$ (ms), 4~GHz & $T_1^{\\rm qp}$ (ms), 5~GHz & "
             "$1/(\\xqp\\omega_q)$ (ms), 5~GHz \\\\\\midrule\n")
    for x, a, b, c in rows:
        fh.write(f"{sci_tex(x, 2)} & {fmt(a)} & {fmt(b)} & {fmt(c)} \\\\\n")
    fh.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

# ============ p3_03 figure: the qubit gauge per device ============
# Thermal floor (Chapter ch:qplatforms, Eqs. eq:qp_peq, eq:qp_pth): p_eq = 1/(1+exp(hf/kT)), p_th = p_eq t_g/T1.
# Transmon reading of p3_03 section sec:qubitfloor: f = 5 GHz, own temperature 35 mK (Jin et al. 2015), T1 = 68 us (Willow mean),
# t_g = 40 ns (illustrative), two-qubit error 1e-3 (illustrative).
# Ion devices: ONLY values traceable to a sentence of the primary paper (checked 2026-10-02):
#   Hughes et al., arXiv:2510.17286, abstract: electronically controlled 40Ca+ two-qubit gates "with an estimated error of
#     8.4(7) x 10^-5" (subspace leakage-error randomized benchmarking, SLERB).
#   Ransford et al., arXiv:2511.05465, abstract: Helios 137Ba+, "average infidelities of ... 7.9(2) x 10^-4 for two-qubit gates",
#     averaged over all operational zones.
# Their hyperfine records are not thermalised: the thermal floor of the held record lies off the axis (arrow).
fq, Tq, T1q, tg, pq = 5e9, 0.035, 68e-6, 40e-9, 1e-3
Mq = C.h * fq / (C.k * Tq); peq = 1 / (1 + np.exp(Mq)); pth = peq * tg / T1q
print(f"transmon: M {Mq:.3f}, p_eq {peq:.3e}, p_th {pth:.3e}")
plat = [("transmon reading (5 GHz, 35 mK)", 1e-3, pth),
        ("Oxford Ionics, Ca$^+$ electronic", 8.4e-5, None),
        ("Quantinuum Helios, Ba$^+$ laser", 7.9e-4, None)]
fig, (a1, a2) = plt.subplots(1, 2, figsize=(S.TEXTW, 2.2), gridspec_kw=dict(width_ratios=[1.45, 1]))
XL = (1e-4, 300)
for i, (nm, p, fl) in enumerate(plat):
    eps = -np.log(1 - p); th = 1e-2 / eps
    y = len(plat) - 1 - i
    lo = fl / eps if fl else XL[0]
    a1.plot([lo, th], [y, y], color=S.LIGHT, lw=2.5, solid_capstyle="butt", zorder=1)
    if fl:
        a1.plot(fl / eps, y, "D", color=S.GR, ms=5, zorder=3)
        a1.text(fl / eps, y + 0.22, f"{fl/eps:.1e}".replace("e-0", "e-"), ha="center", fontsize=6, color=S.GR)
    else:
        a1.annotate("", xy=(XL[0] * 1.05, y), xytext=(XL[0] * 6, y), arrowprops=dict(arrowstyle="->", color=S.GR, lw=0.9))
        a1.text(XL[0] * 1.3, y + 0.22, "floor off axis", ha="left", fontsize=5.5, color=S.GR)
    a1.plot(1, y, "o", color=S.IAM, ms=6, zorder=3)
    a1.plot(th, y, "|", color=S.DATA, ms=11, mew=1.6, zorder=3)
    a1.text(th, y + 0.22, f"{th:.1f}" if th < 100 else f"{th:.0f}", ha="center", fontsize=6, color=S.DATA)
    print(f"{nm}: eps {eps:.3e}  floor at {fl/eps if fl else float('nan'):.3e}  threshold at {th:.2f}")
a1.set_yticks(range(len(plat))); a1.set_yticklabels([n[0] for n in plat][::-1], fontsize=6)
a1.set_xscale("log"); a1.set_xlim(*XL); a1.set_ylim(-0.6, len(plat) - 0.3)
a1.axvline(1, color=S.IAM, lw=0.6, ls=":")
a1.set_xlabel(r"reading $A=\varepsilon/\varepsilon_{\rm device}$ (device as built $=1$)")
a1.set_title("Qubit gauge: thermal floor, as built, threshold", fontsize=7)
S.panel_letter(a1, "a", dx=-0.48)
p = np.logspace(-5, -1, 200); a2.plot(p, 100 * (-np.log(1 - p) / p - 1), color=S.IAM)
for nm, pp, fl in plat:
    a2.plot(pp, 100 * (-np.log(1 - pp) / pp - 1), "o", color=S.DATA, ms=3)
a2.axvline(1e-2, color=S.LIGHT, lw=0.8, ls="--"); a2.text(1.15e-2, 0.03, "$p=10^{-2}$", fontsize=6, color=S.GR)
print(f"(eps-p)/p at p=1e-2: {100*(-np.log(1-1e-2)/1e-2-1):.3f} %")
a2.set_xscale("log"); a2.set_yscale("log"); a2.set_ylim(1e-3, 10)
a2.set_xlabel("two-qubit error $p_{2Q}$"); a2.set_ylabel(r"$(\varepsilon-p)/p$ (%)")
a2.set_title(r"$\varepsilon=-\ln(1-p)$ equals $p$ to $p/2$", fontsize=7)
S.panel_letter(a2, "b", dx=-0.22)
fig.tight_layout(); S.save(fig, "part3", "fig_qubit_gauge")

# ============ p3_06 table: the scales at the gate and the floor against junction temperature ============
k = C.k; Tj = 348.15
with open(TAB / "tab_chip_scales.tex", "w") as fh:
    fh.write("% generated by docs/book/figscripts/fig_p3_extra.py; do not edit by hand\n")
    fh.write("\\begin{table}[htbp]\\centering\\small\n\\caption{The scales at a CMOS gate, and the Landauer floor $\\kB T_j\\ln2$ at three "
             "junction temperatures: the floor moves with the chip's own $T_j$. \\calc}\\label{tab:chip_scales}\n")
    fh.write("\\begin{tabular}{@{}ll@{}}\\toprule\n")
    for TT in (300.0, Tj):
        fh.write(f"subthreshold swing $(\\kB T/q)\\ln10$, {TT:.0f}~K & {1e3*k*TT/C.e*np.log(10):.1f}~mV/decade \\\\\n")
    fh.write("\\midrule\n")
    for tc in (40.0, 75.0, 105.0):
        TT = 273.15 + tc; E = k * TT * np.log(2)
        fh.write(f"Landauer floor $\\kB T_j\\ln2$, $T_j={tc:.0f}\\,^\\circ$C & {sci_tex(E,3)}~J $=${E/C.e:.4f}~eV ({100*(TT/Tj-1):+.1f}\\,\\% from 75\\,$^\\circ$C) \\\\\n")
        print(f"floor at {tc} C: {E:.4e} J, {100*(TT/Tj-1):+.2f} %")
    fh.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

# ============ p3_07 figure 1: the four floors in their own variables ============
G, hbar, c = C.G, C.hbar, C.c; Msun = 1.98847e30; lP2 = hbar * G / c**3
fig, ax = plt.subplots(1, 4, figsize=(S.TEXTW, 2.15))
M = np.logspace(0, 10, 50) * Msun
Sbh = 4 * np.pi * G * M**2 / (hbar * c); Ah = 16 * np.pi * G**2 * M**2 / c**4
ax[0].plot(M / Msun, Sbh / (Ah / lP2), color=S.GR); ax[0].set_xscale("log"); ax[0].set_ylim(0, 0.5)
ax[0].set_xlabel(r"$M/M_\odot$"); ax[0].set_ylabel(r"$S/(k_BA/\ell_P^2)$"); ax[0].set_title("horizon: 1/4", fontsize=7)
print(f"S/(A/lP^2) = {np.mean(Sbh/(Ah/lP2)):.6f}")
TT = np.linspace(4, 400, 200); ax[1].plot(TT, 1e3 * k * TT / C.e * np.log(10), color=S.GR)
for t0 in (300.0, Tj):
    v = 1e3 * k * t0 / C.e * np.log(10); ax[1].plot(t0, v, "o", color=S.DATA, ms=3.5)
    ax[1].annotate(f"{v:.1f}", (t0, v), xytext=(-16, 6), textcoords="offset points", fontsize=6)
ax[1].set_xlabel("$T$ (K)"); ax[1].set_ylabel("swing (mV/decade)"); ax[1].set_title("gate: $(k_BT/q)\\ln 10$", fontsize=7)
Mx = np.linspace(0, 20, 300); ax[2].semilogy(Mx, 1 / (1 + np.exp(Mx)), color=S.GR)
for TT in (0.035, 0.015):                       # transmon at 5 GHz: own temperature 35 mK (Jin et al. 2015), refrigerator 15 mK
    mm = C.h * 5e9 / (C.k * TT); pe = 1 / (1 + np.exp(mm)); ax[2].plot(mm, pe, "o", color=S.DATA, ms=3.5)
    ax[2].annotate(f"{TT*1e3:.0f} mK: {pe:.1e}", (mm, pe), xytext=(4, 4), textcoords="offset points", fontsize=6)
    print(f"qubit thermal floor at {TT*1e3:.0f} mK: M {mm:.2f}, p_eq {pe:.3e}")
ax[2].set_xlabel(r"$M=hf/k_BT$"); ax[2].set_ylabel(r"$p_{\rm eq}$"); ax[2].set_title(r"qubit: $1/(1+e^{M})$", fontsize=7)
x = np.linspace(0, 6, 200); e0 = 1 / (1 + np.exp(x)); ax[3].plot(x, e0, color=S.GR)
e0m = CANON["eps0_meth"]["value"]; ax[3].plot(EH, e0m, "o", color=S.DATA, ms=3.5)   # chain eps0 = 0.032
ax[3].annotate(f"{EH} $k_BT$: {e0m:.3f}", (EH, e0m), xytext=(-4, 12), textcoords="offset points", fontsize=6)
ax[3].set_xlabel(r"$E_{\rm hold}/k_BT$"); ax[3].set_ylabel(r"$\varepsilon_0$"); ax[3].set_title("chromatin: Boltzmann", fontsize=7)
print(f"eps0 = {e0m:.4f}, H(eps0) = {H2(e0m):.4f} bits")
for i, a in enumerate(ax):
    S.panel_letter(a, "abcd"[i], dx=-0.30)
fig.tight_layout(w_pad=0.6); S.save(fig, "part3", "fig_four_floors")

# ============ p3_07 figure 2: the cell gauge A = H(eps)/(P H(eps0)) ============
Hf = H2(e0m); eh = 1e-3 + np.linspace(0, 0.499, 600)
A = H2(eh) / (P * Hf)
from scipy.optimize import brentq
e_h = brentq(lambda e: H2(e) - P * Hf, e0m, 0.5)
fig, ax = plt.subplots(figsize=(0.62 * S.TEXTW, 2.7))
ax.plot(eh, A, color=S.IAM)
for e, a_, lab_ in ((e0m, 1 / P, f"floor: $\\varepsilon_0$ = {e0m:.3f}, A = {1/P:.3f}"),
                    (e_h, 1.0, f"healthy neutrophil: $\\varepsilon$ = {e_h:.4f}, A = 1"),
                    (0.5, 1 / (P * Hf), f"full surface: $\\varepsilon$ = 1/2, A = {1/(P*Hf):.2f}")):
    ax.plot(e, a_, "o", color=S.DATA, ms=4)
    ax.annotate(lab_, (e, a_), xytext={0: (10, -12), 1: (10, 10), 2: (-150, 4)}[[e0m, e_h, 0.5].index(e)], textcoords="offset points", fontsize=6.5)
print(f"healthy eps {e_h:.4f}; floor A {1/P:.3f}; full A {1/(P*Hf):.3f}")
ax.axhspan(0.95, 1.05, color=S.ALT, alpha=0.15, lw=0)
ax.set_xlabel(r"copy error per site per copy $\varepsilon$"); ax.set_ylabel(r"IAM-A $=H(\varepsilon)/(P\,H(\varepsilon_0))$")
ax.set_xlim(0, 0.52); ax.set_ylim(0, 4.9)
ax.set_title("The cell gauge: floor left, healthy at 1, full surface right")
fig.tight_layout(); S.save(fig, "part3", "fig_cell_gauge")

# ============ p3_09 figure 2: reference against changed copy error, per pair ============
md = (REPO / "Biological_Physics/MethylPhys/doors/PROC_TUMOUR_01_OUTCOME.md").read_text()
tum = [tuple(float(v) for v in m.groups()) for m in re.finditer(r"\| CRC\d \| ([\d.]+) \| ([\d.]+) \| ([\d.]+) \|", md)]
assert len(tum) == 6, tum
dn = pd.read_csv(REPO / "Biological_Physics/MethylPhys/doors/PROC_DNMT_01_PARTB/dnmt_b_pairs.csv")
fig, ax = plt.subplots(figsize=(0.62 * S.TEXTW, 2.9))
xx = np.array([0.015, 0.06]); ax.plot(xx, xx, color=S.GR, lw=0.8); ax.plot(xx, 1.05 * xx, color=S.GR, lw=0.6, ls=":")
ax.text(0.0395, 0.0365, "equal", fontsize=6, color=S.GR, rotation=33)
ax.plot([t[0] for t in tum], [t[1] for t in tum], "o", color=S.DATA, ms=4.5,
        label=f"colorectal tumour vs adjacent normal (6 patients, median ratio {np.median([t[2] for t in tum]):.3f})")
ax.plot(dn.eps_dmso, dn.eps_treated, "^", color=S.IAM, ms=4.5,
        label=f"DNMT1 block vs vehicle (8 libraries, ratio of entropies {dn.A.min():.2f}–{dn.A.max():.2f})")
print(f"tumour median ratio {np.median([t[2] for t in tum]):.3f}; DNMT-B A {dn.A.min():.3f}-{dn.A.max():.3f}")
ax.set_xlim(0.015, 0.06); ax.set_ylim(0.015, 0.06)
ax.set_xlabel(r"copy error $\varepsilon$, reference (normal tissue; vehicle)")
ax.set_ylabel(r"copy error $\varepsilon$, changed state")
ax.legend(loc="upper left", fontsize=5.8); ax.set_title("Every pair reads above its own reference")
fig.tight_layout(); S.save(fig, "part3", "fig_reach_cell")
