"""Part VI, chapter 'Tools from the sky': the two tables of docs/book/part4/16a_skytools_*.tex.

Run from any directory:  python docs/book/figscripts/make_skytools_tables.py
Writes docs/book/part6/16a_skytools_skystats.tex and docs/book/part6/16a_skytools_map79.tex.

skystats: Met-A and C-score ranges over the six held-out neutrophil arrays, read from the chain's sky run
  Biological_Physics/MethylPhys/reference_floors_v1/sky/sky_neut6_stats.csv (script sky_neut6.py in the same folder).
map79: the 79-row CMB-to-methylome map (origin: Biological_Physics/MethylPhys/doors/CMB_TO_METHYLOME_MAP.md), scored against
  chain v3 on 2 October 2026. The rows are held below as data. Every row that names a number or a data product is checked here
  against the file it comes from; the script stops if a check fails. The status counts are computed from the rows.
"""
import csv, math, re, subprocess, sys, collections
from pathlib import Path
import numpy as np

HERE = Path(__file__).resolve().parent
BOOK, REPO = HERE.parent, HERE.parent.parent.parent
MP = REPO / "Biological_Physics" / "MethylPhys"
SKY = MP / "reference_floors_v1" / "sky"
OUT_STATS, OUT_MAP = BOOK / "part6" / "16a_skytools_skystats.tex", BOOK / "part6" / "16a_skytools_map79.tex"

# ---------------------------------------------------------------- the sky run: six neutrophil arrays
stats = list(csv.DictReader(open(SKY / "sky_neut6_stats.csv")))
arrays = sorted({r["array"] for r in stats if r["map"] == "healthy"})
assert len(arrays) == 6, arrays
maps = {r["map"] for r in stats}
assert {"healthy", "blur2pct", "local5pct", "null"} <= maps, maps
def rng(m, col):
    v = [float(r[col]) for r in stats if r["map"] == m]
    assert len(v) == 6, (m, col, len(v))
    return min(v), max(v)
SPEC = [("healthy", r"healthy (6 arrays)"), ("blur2pct", r"2\,\% blur everywhere (6 arrays)"), ("local5pct", r"5\,\% blur, 10 regions (6 arrays)")]
L = [r"% generated by docs/book/figscripts/make_skytools_tables.py from reference_floors_v1/sky/sky_neut6_stats.csv; do not edit by hand",
     r"\begin{center}\small", r"\begin{tabular}{@{}lcc@{}}\toprule", r"specimen & Met-A & C-score \\\midrule"]
for m, name in SPEC:
    a, c = rng(m, "MetA_6000"), rng(m, "C_6000")
    L.append(f"{name} & {a[0]:.3f}--{a[1]:.3f} & {c[0]:.2f}--{c[1]:.2f} \\\\")
L += [r"\bottomrule\end{tabular}", r"\end{center}"]
OUT_STATS.write_text("\n".join(L) + "\n")

# ---------------------------------------------------------------- checks behind the rows of the map
readme = (SKY / "README.md").read_text()
assert "Each array is read against the other five" in readme                                   # rows 22, 31
cd_arrays = {r["array"] for r in csv.DictReader(open(SKY / "cd_neut.csv"))}
assert len(cd_arrays) == 6, cd_arrays                                                          # row 23
assert "reads as female" in readme and "chrX" in readme                                        # rows 16, 38, 57
clus = {r["array"]: float(r["map_clustering"]) for r in stats if r["map"] == "healthy"}
assert max(clus, key=clus.get) == "GSM2998057"                                                 # the female array lights up
nside = int(np.load(SKY / "sky_neut6_maps.npz")["nside"])                                      # row 15: maps on HEALPix rings
assert (MP / "atlas" / "healpix_mapping" / "iamatlas_cpg_to_healpix_nside128.npy").exists()
tum = (MP / "doors" / "PROC_TUMOUR_01_OUTCOME.md").read_text()
assert re.search(r"tumour higher in \*\*3/4\*\*", tum)                                         # row 49
sop = (MP / "sop" / "MethylPhys_CPG_SOP_v3.md").read_text()
assert "8 blood groups by NNLS" in sop                                                         # row 1
eps0, M = 1 / (1 + math.exp(3.41)), 54000 / (8.314462618 * 310.15)                             # row 33
assert abs(eps0 - 0.0320) < 5e-4 and f"{M:.2f}" == "20.94", (eps0, M)
chk = subprocess.run([sys.executable, str(REPO / "docs/verification/scripts/verify_astrogenetics_book.py")], cwd=REPO,
                     capture_output=True, text=True).stdout                                    # rows 33, 79
n_ok, n_fail = len(re.findall(r"^OK ", chk, re.M)), re.search(r"FAILURES: (\d+)", chk)
assert n_fail and int(n_fail.group(1)) == 0 and n_ok > 0, chk[-500:]
CHECKS = f"derivation and calculation checks {n_ok}/{n_ok} (verify\\_astrogenetics\\_book.py)"

ROWS = [
    (1, 'Spherical-harmonic decomposition', 'projection of a specimen onto a basis of reference cells', 'in use', 'Stage A solves 8 blood groups; the atlas holds the full basis'),
    (2, 'Monopole, dipole, low multipoles', 'monopole = Met-A (mean over identity sites); sex shows as a chrX patch', 'in use', 'Fig. sky-what-it-sees d'),
    (3, 'Cosmic variance', 'cell-count floor: finite genome copies in a specimen', 'calculated', 'Ch. sky; not in the chain; needed for plasma'),
    (4, 'Frequency coverage', 'more than one mark or assay per cell (5mC, 5hmC; arrays and single molecules)', 'partial', 'Met-A (arrays) and IAM-A (single molecules) read one cell two ways'),
    (5, 'Beam modeling', 'per-probe response from sequence context', 'not built', 'root fix for platform transfer'),
    (6, 'Bandpass calibration', 'bisulfite conversion, probe-type normalization', 'in use', 'Stages 0-1; conversion threshold still to calibrate'),
    (7, 'Gain calibration and drift', 'same-run tare against healthy references', 'in use', 'Stage T: median tare; noise index gates the state; slide tare from control DNA planned'),
    (8, 'Polarization-angle calibration', 'strand orientation', 'not built', ''),
    (9, 'Scanning strategy', 'sampling design of studies across many people', 'out', 'the method reads one specimen at a time'),
    (10, 'Time-ordered data', 'IDAT intensities and control probes', 'in use', 'Stage 1'),
    (11, 'De-glitching and data cuts', 'detection masking, intake gate', 'in use', 'Stage 0'),
    (12, 'Correlated noise', 'array-position and scanner noise', 'partial', 'array noise index N; no position model'),
    (13, 'Map-making', 'intensity to beta', 'in use', 'Stage 1, bit-identical reruns'),
    (14, 'Transfer function', 'how much real signal the deconvolver absorbs', 'measured', 'Ch. separation; no module'),
    (15, 'HEALPix pixelization', 'genome order laid on HEALPix rings', 'built, not in chain', 'maps in this chapter; the C-score works along the genome directly'),
    (16, 'Masks and apodization', 'SNP, cross-reactive and undetected probes; sex chromosomes', 'partial', 'probe masks in use; whole-array maps need a sex mask (this chapter)'),
    (17, 'Cut-sky mode coupling', 'bias of genome-distance correlations from masked sites', 'not built', ''),
    (18, 'Galactic foregrounds', 'composition, sex, batch, age, smoking', 'partial', 'composition and batch (tare) in use; sex measured here; age and smoking not read'),
    (19, 'Extragalactic foregrounds', 'inflammation, drugs, recent illness', 'not built', 'DNMT1 inhibitor is the first known injected foreground'),
    (20, 'Second component separation', 'an independent solver', 'built, not in chain', 'one solver; a second (ILC-style) was built and cut'),
    (21, 'Foreground marginalization', 'composition and tare uncertainty carried into A', 'not built', 'readings are point values with a detection limit'),
    (22, 'Split maps, cross-spectra', 'held-out reference arrays; repeat specimens', 'in use', 'each array read against the other five; repeats being measured in development'),
    (23, 'Pseudo-Cl on a masked sky', 'genome-distance spectrum C(d) inside one specimen', 'partial', 'measured on 6 neutrophil arrays (this chapter); masks not yet handled'),
    (24, 'Quadratic maximum likelihood', 'per-arm or per-domain spectrum', 'not built', ''),
    (25, 'Bandpowers', 'log-spaced genome-distance bins', 'not built', ''),
    (26, 'Beam and calibration nuisances', 'probe response and conversion as nuisance terms', 'not built', ''),
    (27, 'Low-l likelihood', 'few-region signals', 'not built', ''),
    (28, 'High-l likelihood', 'distance of one specimen from a group of people (Mahalanobis)', 'out', 'a statistic over many people'),
    (29, 'Covariance matrices', 'per-site covariance for one cell', 'partial', 'per-site shrunk SD among healthy references; no off-diagonal terms'),
    (30, 'End-to-end simulation', 'constructed specimens: mixtures, known damage', 'in use', '2 \\% and 5 \\% blur, DNA mixtures'),
    (31, 'Null tests', 'healthy-minus-healthy, same array twice, replicate pairs', 'in use', 'null map in this chapter'),
    (32, 'Goodness of fit, look-elsewhere', 'pre-registration and correction for every look', 'reserved', 'for commissioning and evidence runs'),
    (33, 'Boltzmann solver', 'the physics floor: $\\varepsilon_0$ = 1/(1+exp(E\\_hold/kT)), M = 20.94', 'in use', 'IAM-A floor; @CHECKS@'),
    (34, 'Recombination physics', 'the pattern a cell holds after differentiation', 'analogy', ''),
    (35, 'Line-of-sight integration', 'lineage history integrated into a mature cell', 'analogy', ''),
    (36, 'Acoustic-peak phenomenology', 'a reading guide for methylation features', 'not built', ''),
    (37, 'MCMC and posterior geometry', 'posteriors for the atlas; per-reading intervals', 'partial', 'atlas v2 is a posterior; readings carry no posterior yet'),
    (38, 'Degeneracies', 'composition against signal; sex against X', 'partial', 'measured in composition solves; sex found here'),
    (39, 'Priors', 'disease and family-history priors', 'refused', "no prior from other people's outcomes"),
    (40, 'Profile against marginal', 'best-fit fraction against fraction volume', 'not built', ''),
    (41, 'Multimodal posteriors', 'more than one solution for one specimen', 'not built', ''),
    (42, 'Bayesian evidence', 'which tissue of origin explains one person', 'not built', 'per person, not a classifier'),
    (43, 'Tension metrics', 'how far two readings of one person disagree', 'not built', 'Met-A against IAM-A is the first pair'),
    (44, 'Lensing smoothing', 'aging smooths the held pattern', 'analogy', ''),
    (45, 'Four-point reconstruction', 'coordinated four-site changes', 'not built', ''),
    (46, 'Lensing power spectrum', "aging's change of the genome-distance spectrum", 'not built', ''),
    (47, 'Delensing', 'subtracting an age term', 'refused', 'readings are annotated, never de-aged'),
    (48, 'External cross-correlation', 'expression, imaging, chromatin', 'not built', ''),
    (49, 'E/B separation', '5mC against 5hmC (oxidative bisulfite)', 'partial', 'tumor excess kept after 5hmC removal in 3 of 4 pairs'),
    (50, 'B-mode taxonomy', 'what a 5hmC signal can contain', 'not built', ''),
    (51, 'Reionization bump', 'early-life reprogramming', 'analogy', ''),
    (52, 'Birefringence', 'oxidation chain 5mC to 5caC', 'analogy', ''),
    (53, 'Bispectrum', 'three-site shapes', 'not built', ''),
    (54, 'Trispectrum', 'four-site events', 'not built', ''),
    (55, 'Minkowski functionals', 'topology of the residual map', 'not built', ''),
    (56, 'Phase statistics', 'ordering at fixed amplitude', 'not built', ''),
    (57, 'Isotropy tests', 'per-chromosome residual means', 'built, not in chain', 'this chapter: chrX in a female array'),
    (58, 'Parity asymmetry', 'strand and chromosome parity', 'not built', ''),
    (59, 'Alignment tests', 'shared axes between chromosomes', 'not built', 'look-elsewhere applies'),
    (60, 'Matched circles', 'distant co-regulated pairs', 'analogy', ''),
    (61, 'Look-elsewhere discipline', 'pre-registration', 'reserved', 'for commissioning and evidence runs'),
    (62, 'Integrated Sachs-Wolfe', 'late-life drift', 'analogy', ''),
    (63, 'Rees-Sciama', 'nonlinear corrections', 'does not translate', ''),
    (64, 'Thermal SZ', 'inflammation reshaping the methylome', 'analogy', ''),
    (65, 'Kinetic SZ', 'clonal expansion', 'analogy', ''),
    (66, 'Patchy reionization', 'patchy senescence', 'analogy', ''),
    (67, 'Infrared background', 'turnover background', 'not built', ''),
    (68, 'Rayleigh scattering', 'none', 'does not translate', ''),
    (69, 'Spectral distortions', "departures from the physics floor's predicted spectrum", 'open', ''),
    (70, 'BAO combination', 'adding fragmentation, chromatin, expression', 'not built', ''),
    (71, 'Distance ladder', 'age clock trained on large groups of people of known age', 'out', 'per-array age inversion refused'),
    (72, 'BBN cross-check', 'germline and inheritance checks', 'not built', ''),
    (73, 'Large-scale structure', 'structure across large groups of people', 'out', 'read across many people, not one cell'),
    (74, 'Joint likelihoods', "one person's readings with shared covariance", 'not built', ''),
    (75, 'Compressed likelihoods', 'released per-reading likelihoods', 'not built', ''),
    (76, 'Emulators', 'fast atlas surrogate', 'not built', ''),
    (77, 'Simulation-based inference', 'inference from constructed specimens', 'not built', ''),
    (78, 'Blinding', 'analysis fixed before labels are seen', 'reserved', 'for commissioning and evidence runs'),
    (79, 'Reproducibility', 'bit-identical calibration; tests that read the frozen files', 'in use', '@CHECKS@'),
]

ROWS = [(n, a, b, s, w.replace("@CHECKS@", CHECKS)) for n, a, b, s, w in ROWS]
assert [r[0] for r in ROWS] == list(range(1, 80))
ORDER = ["in use", "built, not in chain", "partial", "calculated", "measured", "reserved", "not built", "open", "analogy", "refused",
         "out", "does not translate"]
cnt = collections.Counter(r[3] for r in ROWS)
assert set(cnt) <= set(ORDER), set(cnt) - set(ORDER)
for bad in ("cohort", "population"):
    assert not any(bad in " ".join(map(str, r)).lower() for r in ROWS), bad
L = [r"% generated by docs/book/figscripts/make_skytools_tables.py (rows held in the script; checks read the chain's sky run,",
     r"% reference_floors_v1/sky, the HEALPix mapping in atlas/healpix_mapping, and verify_astrogenetics_book.py); do not edit by hand",
     r"\newcommand{\mapcounts}{" + "; ".join(f"{k} {cnt[k]}" for k in ORDER if cnt[k]) + "}",
     r"\begin{center}\scriptsize",
     r"\begin{longtable}{@{}r p{0.21\textwidth} p{0.32\textwidth} p{0.12\textwidth} p{0.18\textwidth}@{}}",
     r"\caption{The 79-row CMB-to-methylome map, scored against chain v3 on 2 October 2026.}\label{tab:map79}\\",
     r"\toprule \# & CMB tool & counterpart in the cell & status & where \\\midrule\endfirsthead",
     r"\toprule \# & CMB tool & counterpart in the cell & status & where \\\midrule\endhead"]
for i, (n, a, b, s, w) in enumerate(ROWS):
    L.append(f"{n} & {a} & {b} & {s} & {w} \\\\" + (" \\rowrule" if i < len(ROWS) - 1 else ""))
L += [r"\bottomrule", r"\end{longtable}", r"\end{center}"]
txt = "\n".join(L) + "\n"
assert txt.count("{") == txt.count("}")
OUT_MAP.write_text(txt)
print(f"wrote {OUT_STATS.relative_to(REPO)} and {OUT_MAP.relative_to(REPO)}: {len(ROWS)} rows; {CHECKS}; sky maps NSIDE {nside}")
print("counts:", "; ".join(f"{k} {cnt[k]}" for k in ORDER if cnt[k]))
