"""Appendix G: the predictions register, typeset from CANON/predictions_triage_2026-10-02.json.

Run from any directory:  python docs/book/figscripts/make_app_G.py
Writes docs/book/appendices/app_G_predictions_register.tex. Nothing in the table is typed by hand:
  * every row is a register entry whose verdict is KEEP, CORRECT or TESTED;
  * statement, test and date, and falsifier come from the JSON, after the edits in app_G_overrides.json
    (each edit must match its field exactly once, or the script stops);
  * values that an override changes are recomputed here and checked (decoherence time, E_G shift);
  * the chapter number (C1, Q2, ...) is read from the bracketed register IDs in part5/p5_07_predictions.tex;
  * the count table counts all 519 verdicts by domain.
A final lint stops the script if a draft, method name, hold note or correction phrase survives in the rendered text.
"""
import json, re, sys, collections
from pathlib import Path
import numpy as np
import scipy.constants as sc

HERE = Path(__file__).resolve().parent
BOOK, REPO = HERE.parent, HERE.parent.parent.parent
sys.path.insert(0, str(HERE))
from _texify import texify, check  # noqa: E402

TRIAGE = REPO / "CANON" / "predictions_triage_2026-10-02.json"
OVER = HERE / "app_G_overrides.json"
CHAP = BOOK / "part5" / "p5_07_predictions.tex"
OUT = BOOK / "appendices" / "app_G_predictions_register.tex"

DOMAINS = [("COS", "Cosmology and gravitation"), ("PAR", "Particle physics and fundamental limits"),
           ("QUB", "Qubits and quantum measurement"), ("SEM", "Semiconductor chips"), ("OTH", "Quantum foundations")]
VERB = {"KEEP": "kept", "CORRECT": "restated", "TESTED": "tested", "DUP": "merged", "DROP": "not listed"}
LISTED = ("KEEP", "CORRECT", "TESTED")
FIELDS = ("statement", "test_and_date", "falsified_if")

reg = json.load(open(TRIAGE))
ov = {k: v for k, v in json.load(open(OVER)).items() if not k.startswith("_")}
assert len(reg) == 519, len(reg)
byid = {e["pid"]: e for e in reg}

# ---- recompute the values the overrides change ----
def tau_iam(m, T=0.01, rho=2200.0):
    R = (3 * m / (4 * np.pi * rho)) ** (1 / 3)
    EG = sc.G * m * m / R
    return sc.hbar * sc.k ** 2 * T ** 2 * np.log(2) / EG ** 3

amu = sc.physical_constants["atomic mass constant"][0]
import _cosmo as K  # noqa: E402
a03 = 1 / 1.3
CHECK = {"tau_1e-12kg_s": tau_iam(1e-12), "tau_1e13amu_s": tau_iam(1e13 * amu), "tau_1e14amu_s": tau_iam(1e14 * amu),
         "EG_z0.3_pct": 100 * (K.f(K.LCDM, a03) / K.f(K.IAM, a03) - 1)}
for pid, o in ov.items():
    for key, want in o.get("check", {}).items():
        got = CHECK[key]
        assert abs(got - want) / abs(want) < 0.03, (pid, key, got, want)

# ---- chapter numbers from the predictions chapter ----
chap = collections.defaultdict(list)
s7 = CHAP.read_text()
for m in re.finditer(r"\\textbf\{([A-Z]\d+)\.\}(.*?)\[((?:[A-Z]{3}-\d{3})(?:,\s*(?:[A-Z]{3}-)?\d{3})*)\]", s7, re.S):
    pre = None
    for tok in (t.strip() for t in m.group(3).split(",")):
        if "-" in tok:
            pre, pid = tok.split("-")[0], tok
        else:
            pid = f"{pre}-{tok}"
        if m.group(1) not in chap[pid]:
            chap[pid].append(m.group(1))

# ---- apply overrides ----
rows, excluded = [], []
for e in reg:
    if e["verdict"] not in LISTED:
        continue
    o = ov.get(e["pid"], {})
    if "exclude" in o:
        excluded.append((e["pid"], e["verdict"], o["exclude"]))
        continue
    r = {f: e[f] for f in FIELDS}
    for f in FIELDS:
        for old, new in o.get(f, []):
            n = r[f].count(old)
            assert n == 1, f"{e['pid']} {f}: override text found {n} times - fix or delete the override"
            r[f] = r[f].replace(old, new)
    r.update(pid=e["pid"], verdict=e["verdict"], open=o.get("open"), dom=e["pid"].split("-")[0])
    rows.append(r)
for pid in ov:
    assert pid in byid and byid[pid]["verdict"] in LISTED, f"override for {pid}: not a listed entry"

LINT = re.compile(r"the quantum-processor report|the semiconductor report|the methylation report|\bpaper\b|\bnote\b|ON HOLD|pending|recompute|\bcorrect(ed|ion)|withdrawn|"
                  r"\bauthor|\bEq\.|\beq\. |\(not [\d~]|\bclaimed\b|to be decided|Wide Domains|Substrate Inversion|"
                  r"Motional Heating Inversion", re.I)
bad = [(r["pid"], f, LINT.search(r[f]).group(0)) for r in rows for f in FIELDS if LINT.search(r[f])]
bad += [(r["pid"], "open", LINT.search(r["open"]).group(0)) for r in rows if r["open"] and LINT.search(r["open"])]
assert not bad, bad

# ---- typeset ----
def cell(s):
    s = s.strip()
    return texify(s) if s else "---"

L = []
L.append(r"% Generated by docs/book/figscripts/make_app_G.py from CANON/predictions_triage_2026-10-02.json"
         r" and docs/book/figscripts/app_G_overrides.json. Do not edit by hand.")
L.append(r"\chapter{The predictions register}\label{app:register}")
L.append("")
L.append(r"This appendix lists every entry of the predictions register that stands as a prediction or as a completed test.")
L.append(r"The distinct predictions drawn from it, with their test dates, are in Chapter~\ref{ch:predictions}; the number in")
L.append(r"brackets after a register identifier (C1, Q2, \ldots) is the prediction of that chapter which the entry belongs to.")
L.append(r"Each entry carries one verdict. \emph{Kept}: the entry stands as registered. \emph{Restated}: the entry stands with")
L.append(r"the values recomputed for this book. \emph{Tested}: the comparison with data has been made, and the row gives its outcome.")
L.append(r"Rows marked kept or restated are \prediction; rows marked tested report a \measured\ comparison. A row that also")
L.append(r"carries \openprob\ names the part of the test that cannot yet be made. The cell entries of the register wait for the")
L.append(r"commissioning of each cell type in Part~\ref{part:4} and are not listed.")
L.append("")

cnt = collections.Counter((e["pid"].split("-")[0], e["verdict"]) for e in reg)
lst = collections.Counter((r["dom"], r["verdict"]) for r in rows)
L.append(r"\begin{table}[htbp]\centering\small")
L.append(r"\caption{Verdicts on the 519 register entries outside the cell domain, by domain. Merged entries repeat another"
         r" entry; entries not listed are definitions, restatements or interpretations, or name no test. The last column"
         r" counts the rows of this appendix. \observed}\label{tab:register_counts}")
L.append(r"\begin{tabular}{@{}lrrrrrrr@{}}\toprule")
L.append(r"domain & kept & restated & tested & merged & not listed & total & rows here\\\midrule")
tot = collections.Counter()
for code, name in DOMAINS:
    vals = [cnt[(code, v)] for v in ("KEEP", "CORRECT", "TESTED", "DUP", "DROP")]
    here = sum(lst[(code, v)] for v in LISTED)
    for v, x in zip(("KEEP", "CORRECT", "TESTED", "DUP", "DROP"), vals):
        tot[v] += x
    tot["here"] += here
    L.append(f"{name} & " + " & ".join(map(str, vals)) + f" & {sum(vals)} & {here}\\\\")
tv = [tot[v] for v in ("KEEP", "CORRECT", "TESTED", "DUP", "DROP")]
L.append(r"\midrule all & " + " & ".join(map(str, tv)) + f" & {sum(tv)} & {tot['here']}\\\\\\bottomrule")
L.append(r"\end{tabular}\end{table}")
assert sum(tv) == 519
if excluded:
    L.append("")
    L.append(f"Of the {sum(tot[v] for v in LISTED)} entries with a standing verdict, {len(excluded)} are not listed: they repeat a"
             r" comparison that another row states, record an outcome that is not a prediction, or rest on a compilation"
             r" with no primary data set named.")
L.append("")

COLS = (r"{@{}>{\raggedright\arraybackslash}p{0.10\textwidth}>{\raggedright\arraybackslash}p{0.40\textwidth}"
        r">{\raggedright\arraybackslash}p{0.19\textwidth}>{\raggedright\arraybackslash}p{0.19\textwidth}"
        r">{\raggedright\arraybackslash}p{0.07\textwidth}@{}}")
HEAD = r"entry & statement & test and date & falsified if & verdict\\\midrule"
for code, name in DOMAINS:
    rr = sorted((r for r in rows if r["dom"] == code), key=lambda r: r["pid"])
    if not rr:
        continue
    L.append(r"\section{" + name + "}")
    L.append(r"{\footnotesize\begin{longtable}" + COLS)
    L.append(r"\toprule " + HEAD + r"\endfirsthead")
    L.append(r"\toprule " + HEAD + r"\endhead")
    L.append(r"\bottomrule\endfoot")
    for r in rr:
        cid = chap.get(r["pid"])
        ident = r["pid"].replace("-", "-\\allowbreak{}") + (f" ({', '.join(cid)})" if cid else "")
        st = cell(r["statement"])
        if r["open"]:
            st += r" \openprob\ " + texify(r["open"])
        line = f"{ident} & {st} & {cell(r['test_and_date'])} & {cell(r['falsified_if'])} & {VERB[r['verdict']]}\\\\"
        err = check(line)
        assert err is None, (r["pid"], err, line)
        L.append(line)
    L.append(r"\end{longtable}}")
    L.append("")

tex = "\n".join(L) + "\n"
assert check(tex) is None, check(tex)
OUT.write_text(tex)
print(f"wrote {OUT.relative_to(REPO)}: {len(rows)} rows, {len(excluded)} not listed, "
      f"{sum(1 for r in rows if r['pid'] in chap)} with a chapter number")
for k, v in CHECK.items():
    print(f"check {k} = {v:.4g}")


# --- post-process (2026-10-02): keep the generated table inside the text width
import re as _re
_f = OUT
_s = open(_f, encoding="utf-8").read()
_s = _re.sub(r"p\{([\d.]+)\\textwidth\}", lambda m: "p{%.3f\\textwidth}" % (float(m.group(1)) * 0.96), _s)
_s = _s.replace("{\\footnotesize\\begin{longtable}", "{\\footnotesize\\setlength{\\tabcolsep}{3pt}\\begin{longtable}")
_s = _s.replace("\\begin{tabular}{@{}lrrrrrrr@{}}", "\\begin{adjustbox}{max width=\\textwidth}\n\\begin{tabular}{@{}lrrrrrrr@{}}", 1)
_i = _s.find("\\begin{adjustbox}")
if _i >= 0:
    _j = _s.find("\\end{tabular}", _i); _s = _s[:_j] + "\\end{tabular}\n\\end{adjustbox}" + _s[_j + len("\\end{tabular}"):]
_s = _re.sub(r"(?<=[A-Za-z+0-9])/(?=[A-Za-z])", "/\\\\allowbreak{}", _s)
open(_f, "w", encoding="utf-8").write(_s)
