#!/usr/bin/env python3
"""canon_to_tex.py (needs \\usepackage{booktabs,longtable,array}) - write the book appendix 'The master table and glossary' from CANON/iam_canon.json.
Run by canon_check.py --glossary, so GLOSSARY.md and the book appendix always come from the same file. Output: docs/book/appendices/app_A_canon.tex.
Carried into the book: constants; names with status current / informal; retired names (as a table), except block-severity names, which never appear in the book. Not carried: entries marked
'issue text (not a term)' and 'current (unverified)' Issue 002 glossary prose (kept in the canon file as record)."""
import os, re, json
HERE=os.path.dirname(os.path.abspath(__file__)); ROOT=os.path.dirname(HERE)
C=json.load(open(os.path.join(HERE,"iam_canon.json"),encoding="utf-8"))
U={"β":r"$\beta$","ε":r"$\varepsilon$","φ":r"$\varphi$","μ":r"$\mu$","Σ":r"$\Sigma$","Ω":r"$\Omega$","σ":r"$\sigma$","ν":r"$\nu$","χ":r"$\chi$","Δ":r"$\Delta$",
   "≤":r"$\le$","≥":r"$\ge$","×":r"$\times$","−":"-","≈":r"$\approx$","→":r"$\to$","°":r"$^\circ$","–":"--","—":"---","’":"'","‘":"'","“":"``","”":"''",
   "±":r"$\pm$","·":r"$\cdot$","…":r"\ldots{}","é":r"\'e","ü":r'\"u',"⟨":r"$\langle$","⟩":r"$\rangle$","½":r"$\tfrac12$","₀":r"$_0$","²":r"$^2$","³":r"$^3$"}
def esc(s):
    s=str(s); out=[]
    for ch in s:
        if ch in U: out.append(U[ch])
        elif ch in "&%$#_{}": out.append("\\"+ch)
        elif ch=="~": out.append(r"\textasciitilde{}")
        elif ch=="^": out.append(r"\textasciicircum{}")
        elif ch=="\\": out.append(r"\textbackslash{}")
        elif ord(ch)>127: out.append("?")
        else: out.append(ch)
    return "".join(out)
def readable(k):
    """A retired-name regex as plain words: \\b and \\s* dropped, [Xx] -> X, [- ] -> space."""
    k=k.replace("\\b","").replace("\\s*"," ").replace("\\.",".")
    k=re.sub(r"\[([^\]])[^\]]*\]", lambda m: " " if m.group(1) in "- " else m.group(1), k)
    return re.sub(r"\s+"," ",k).strip()
def main():
    keep=lambda v: v.get("status") in ("current","informal")
    L=["% Generated by CANON/canon_to_tex.py from CANON/iam_canon.json v"+str(C["version"])+" ("+str(C["date"])+"). Do not edit by hand.",
       r"\chapter{The master table and glossary}\label{app:canon}",
       r"Every constant and name in this book is taken from one file, \texttt{CANON/iam\_canon.json}; this appendix is generated from it.",
       r"\section*{The symbols}",
       r"\begin{center}\small\begin{tabular}{p{0.12\textwidth}p{0.8\textwidth}}\toprule",
       r"$A$ & reading $/$ the healthy or as-built reading of the same system, the same meaning in every domain; $A=1$ is healthy, $H_{\min}$ the floor below it\\",
       r"$H_{\min}$ & the floor: chips $k_BT_j\ln2$; qubits the material floor $\varepsilon_{\rm floor}$; cells the cell type's reference floor (Met-A) or $P_{\rm cell}H(\varepsilon_0)$ (IAM-A)\\",
       r"$\varepsilon$ & qubits: $-\ln(1-p_{2Q})$, the gate error in nats; cells: the per-molecule copy error\\",
       r"$M$ & $E/k_BT$ (cells $20.94$; chips $A\ln2$); $M/\ln2$ in Landauer units\\",
       r"$n$ & temperature exponent, $A\propto T^n$; calibrated per class, not derived; not $A$\\\bottomrule",
       r"\end{tabular}\end{center}",
       r"\section*{Constants}", r"{\small\begin{longtable}{>{\raggedright\arraybackslash}p{0.25\textwidth}>{\raggedright\arraybackslash}p{0.12\textwidth}>{\raggedright\arraybackslash}p{0.13\textwidth}>{\raggedright\arraybackslash}p{0.38\textwidth}}\toprule",
       r"name & value & units & derivation and source\\\midrule\endhead"]
    for k,v in C["constants"].items():
        val=v["value"]; val="pending" if val is None else (f"{val:.6g}" if isinstance(val,float) else str(val))
        der=v.get("derivation","")
        if len(val)>16 and not val.replace(".","").replace("-","").isdigit(): der=val+(". "+der if der else ""); val="see right"
        name=esc(k).replace("\\_","\\_\\allowbreak{}")
        src=(" --- "+esc(v["source"])) if v.get("source") else ""
        L.append(name+" & "+esc(val)+" & "+esc(v.get("units","")).replace("\\_","\\_\\allowbreak{}")+" & "+esc(der)+src+"\\\\")
    L+=[r"\bottomrule\end{longtable}}", r"\section*{Names in use}",
        r"{\small\begin{longtable}{>{\raggedright\arraybackslash}p{0.24\textwidth}p{0.7\textwidth}}\toprule", r"name & definition\\\midrule\endhead"]
    for k,v in C["names"].items():
        if keep(v): L.append(f"{esc(k)} & {esc(v['definition'])}{(' \\emph{Note:} '+esc(v['note'])) if v.get('note') else ''}\\\\")
    L+=[r"\bottomrule\end{longtable}}", r"\section*{Retired names}",
        r"{\small\begin{longtable}{>{\raggedright\arraybackslash}p{0.3\textwidth}p{0.64\textwidth}}\toprule", r"retired & use instead\\\midrule\endhead"]
    for k,v in C["names"].items():
        if v.get("status")=="retired": L.append(f"{esc(k)} & {esc(v.get('replaced_by',''))}\\\\")
    for k,v in C["retired"].items():
        if v.get("severity")=="block": continue   # blocked names never appear in the book, not even as retired
        L.append("{}"+esc(readable(k))+" & "+esc(v["replaced_by"])+"\\\\")
    L+=[r"\bottomrule\end{longtable}}"]
    s="\n".join(L)+"\n"; bad=s.count("?")
    o=os.path.join(ROOT,"docs","book","appendices"); os.makedirs(o,exist_ok=True)
    open(os.path.join(o,"app_A_canon.tex"),"w",encoding="utf-8").write(s)
    print("app_canon.tex written:", sum(1 for v in C["names"].values() if keep(v)), "names,", len(C["constants"]), "constants; unmapped chars:", bad)
if __name__=="__main__": main()
