#!/usr/bin/env python3
"""Give each detailed Stage 0 step section in the SOP its operational detail: what it measures on real
arrays, the exact string it prints when it refuses, and what the operator does about it.

The SOP's §11-§19 sections already carry the design (what the step does, its inputs, the math, the CMB
equivalent). What they lacked until 2026-09-23 was the part an operator needs at the bench: the thresholds as
applied in code, what healthy specimens actually measure against them, the refusal strings to search for, and
the fix. That evidence now exists (PROC-STAGE0-02, 732 arrays), so it belongs under the step it governs.

Idempotent: each block is delimited by a marker and replaced in place, so this can run from sop_repoint.py
every time the SOP is regenerated. Run it after sop_stage_links.py.
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
SOP = os.path.join(HERE, "MethylPhys_CPG_SOP.md")
BEGIN = "<!-- OPERATIONAL DETAIL (generated by sop_step_detail.py) -->"
END = "<!-- END OPERATIONAL DETAIL -->"

COMMON = (
    "\n_Evidence for every number in this block: [`PROC_STAGE0_02_OUTCOME.md`](../doors/PROC_STAGE0_02_OUTCOME.md)"
    " — Stage 0 run over 732 healthy whole-blood arrays (GSE87571), per-array results in"
    " [`PROC_STAGE0_02.json`](../kit/results/PROC_STAGE0_02.json)._\n"
)

DETAIL = {
"§11": """**As applied in code.** `step_0_1_idat_arrival(manifest_entry, grn_path, red_path, intake_log_path)` runs
four checks in this order and returns at the first refusal:

| check | rule | refusal |
|---|---|---|
| manifest completeness | all seven of `sentrix_id`, `array_type`, `patient_id`, `intake_date`, `substrate`, `declared_sex`, `declared_chronological_age` present and non-empty | `QUARANTINE_INCOMPLETE_MANIFEST` |
| both channels | Grn and Red both exist and are readable | `QUARANTINE_MISSING_CHANNEL` |
| file size | each IDAT ≥ `MIN_PLAUSIBLE_IDAT_BYTES` = 1,000,000 bytes | `QUARANTINE_TRUNCATED_UPLOAD:<channel>=<bytes>B` |
| array type | the type in the file header must agree with the declared family | `QUARANTINE_ARRAY_TYPE_MISMATCH:declared=…,detected=…` |

**The array type is read, not trusted.** `read_idat_nsnps` reads the IDAT magic and the `nSNPsRead` field only —
it does not decode intensities — and `_infer_platform` maps the count: under 800,000 is `HM450K`, under
1,080,000 is `EPIC_v1`, above that `EPIC_v2`. A 450K array reports **622,399** addresses and an EPIC v1 about
**1,051,943**. Within the EPIC family a v1/v2 disagreement is a note (`ARRAY_SUBTYPE_NOTE`); across families it
is a quarantine, because the probe sets do not correspond.

**Gzipped files.** Public repositories ship `.idat.gz`. The header reader opens gzip transparently. Before
2026-09-23 it did not, which meant the array type read as unreadable on every public download and this gate
silently never fired — the reason a reader should treat "no failures reported" as a question, not an assurance.

**Measured.** All 732 arrays in the reference cohort verified as `HM450K` from their own headers. Three were
refused here, all `QUARANTINE_INCOMPLETE_MANIFEST`, all for the same reason: the depositors publish no age for
those donors. No specimen in the cohort failed on size or channels.

**At the bench.** A missing age or sex is not a formality — Step 0.8 compares the declared sex against the
array, and the age term is removed from the reading downstream. A sample whose metadata is unknown can be
calibrated but cannot be placed.""",

"§12": """**As applied in code.** `step_0_2_manifest_creation(step_0_1_result, questionnaire_answers, manifest_dir,
intake_date)` writes the immutable per-sample manifest and refuses in two cases:

| rule | refusal |
|---|---|
| `array_type` ∈ (`HM450K`, `EPIC_v1`, `EPIC_v2`) — exactly these tokens | `QUARANTINE_MANIFEST_INVALID` with flag `UNKNOWN_ARRAY_TYPE:<value>` |
| `patient_id` is hashed: ≥ 16 characters after removing `-` and `_`, alphanumeric, no spaces, no `@` | `QUARANTINE_MANIFEST_INVALID` with flag `CLEARTEXT_PII:patient_id_not_hashed` |

`450k`, `450K` and `EPIC` are **not** accepted tokens — the check is exact, because a silently-coerced array
type is how a sample gets scored against the wrong probe set. `run_sample.py` hashes a cleartext identifier
before building the entry; a pipeline that builds its own manifest must hash it first. The engine never sees a
name, a date of birth or an accession that identifies a person.

**One `sample_run_id` per intake.** It is a UUID minted here, and it is what the integrity log, the manifest
file and the report all key on. Re-taking the same specimen mints a new run id and leaves the first record
intact.

**The failure mode worth knowing.** This step reads the *result* of Step 0.1, not the caller's dictionary. If
a field is not propagated between the two, this gate sees it as absent and refuses — which is what happened on
2026-09-23 when `patient_id` was dropped in transit: every array in a 732-array cohort came back
`QUARANTINE_MANIFEST_INVALID` with a PII flag, and the cause was two functions disagreeing about a field name.
**A gate that refuses 100 % of anything is reporting on the wiring, not on the specimens.**""",

"§13": """**As applied in code.** `step_0_3_integrity_hash(record, grn_path, red_path, integrity_log_path)` takes the
SHA-256 of both files, compares against every prior intake of the same Sentrix ID in the integrity log, and
stamps one of two statuses:

| what the log shows | status | advances? |
|---|---|---|
| no prior record for this Sentrix ID | `INTEGRITY_OK` | yes |
| a prior record with **identical** hashes | `RE_TRANSMISSION_DETECTED` | **no — held for an operator** |
| a prior record with **different** hashes | `INTEGRITY_OK`, flag `LIKELY_RE_RUN_FRESH_ARRAY` | yes, under a new run id |

The asymmetry is the point. The same bytes arriving twice is a duplicate submission and a human should say
which one counts. Different bytes under the same Sentrix ID is a genuine re-run of that position on a fresh
array, which is normal laboratory practice and advances.

**At the bench.** A legitimate re-analysis of the same files — a re-run of the chain rather than of the array —
should use a separate `--intake-log`, or none. Pointing it at the same log is what produces a hold, and the
hold is correct: from the log's point of view the specimen has already been taken in.

**What a hash does not catch.** Integrity here means *this is the file I logged*, not *this file is intact*. A
file can carry a stable hash, pass the 1 MB floor, and still be truncated inside its compressed stream — one
array in the 732-pair reference download is exactly that, and it is caught two steps later by the decoder, as
`QUARANTINE_CORRUPT_IDAT`. Both checks are needed; neither substitutes for the other.""",

"§14": """**As applied in code.** `step_0_4_control_probe_validation(record, grn_path, red_path, control_summary)`.
When no summary is supplied it calls `extract_control_probes`, which delegates to
[`stage_0_1_qc_handoff.py`](../chain/stage_0_1_qc_handoff.py) — the same decoder Stage 1 uses (methylprep),
reading the control addresses out of the array's own manifest. Nothing but the patient's own array enters.

| metric | construction | threshold | healthy median (n=731) |
|---|---|---|---|
| bisulfite conversion efficiency | per matched BS Conversion I pair (C_i with U_i), C/(C+U) in green; the array's value is the median over the six pairs | `BS_CONVERSION_MIN` = 0.95 | **0.798** (p05 0.740, worst 0.635) |
| hybridisation | `hyb_high_median / hyb_low_median` from the Hyb (High) and Hyb (Low) controls, green | `HYB_HIGH_LOW_MIN_RATIO` = 2.0 | passes on every array |
| extension balance | median green of Extension (C),(G) over median red of Extension (A),(T) | `EXTENSION_BALANCE_RANGE` = (0.2, 5.0) | ≈ 0.73 |

**The bisulfite threshold is reported, not applied.** Every one of 731 healthy arrays sits below 0.95. A gate
that refuses every healthy specimen is not measuring the specimen, so when bisulfite conversion is the *only*
failing metric and `BS_THRESHOLD_CALIBRATED` is False, this step returns
`PROVISIONAL_BS_THRESHOLD_UNCALIBRATED`, Step 0.9 records it as deferred, and the measured value prints on the
report. The threshold will be set from the healthy distribution across several cohorts
([`PROC_STAGE0_04_PREREG.md`](../doors/PROC_STAGE0_04_PREREG.md)) and the flag flipped in the same commit.
Every other metric in this step applies normally: `FAIL_HYB_FAIL` and `FAIL_EXT_FAIL` are hard failures.

**At the bench.** Read a low bisulfite number as information about conversion chemistry on that plate, not as
a refusal. Read a hybridisation or extension failure as a run to repeat.""",

"§15": """**As applied in code.** `step_0_5_detection_pvalue_qc(record, probe_intensities, neg_control_stats)`, with
both inputs from the hand-off. Detection p per probe is
`1 − Φ((I − μ_bg)/σ_bg)` — the SOP's stated formula — where μ_bg and σ_bg come from the **613 NEGATIVE control
probes on the patient's own array**, not from a cohort.

| quantity | value |
|---|---|
| p threshold | `DETECTION_P_THRESHOLD` = 0.01 |
| pass fraction required | `DETECTION_PASS_FRACTION` = 0.99 → `PASS` |
| borderline band | ≥ `DETECTION_BORDERLINE_FRACTION` = 0.95 → `DETECTION_BORDERLINE` |
| below that | `FAIL_LOW_DETECTION` — hard failure |
| healthy median (n=731) | **0.9994**, p05 0.9990, worst **0.9951** |

**The construction matters more than the threshold.** A probe's total intensity is built by Infinium design:
a Type II probe is read at address A in both channels; a Type I probe at addresses A **and B within its own
colour channel**, because the other channel carries only background there. Summing both channels for a Type I
probe understates its signal and drags the pass fraction down — measured on the same array, the naive
construction reads 0.979 and the design-aware one 0.9998. If your detection rates look uniformly poor, check
this before you suspect the specimens.

**At the bench.** Healthy arrays clear 0.99 with two decimal places to spare, so a genuine failure here is far
from normal and points at hybridisation or a degraded specimen — not at configuration.""",

"§16": """**As applied in code.** `step_0_6_bead_count_qc(record, bead_counts)`; bead counts come from the IDAT's own
`n_beads` field via the hand-off, taken as the minimum over the addresses a probe uses.

| quantity | value |
|---|---|
| minimum beads per probe | `BEAD_COUNT_MIN` = 3 |
| fraction required | `BEAD_PASS_FRACTION` = 0.995 → `PASS`, else `WARN_LOW_BEAD_COUNT` |
| healthy median (n=731) | **0.9988**, p05 0.9969, worst 0.9900 |
| arrays below the fraction | 9 of 731 |

**This gate warns; it does not refuse.** A low bead count is a precision statement about part of the array, not
a reason to discard a specimen, so it contributes `borderline` to the Step 0.9 decision and the sample is
scored as `PROCEED_WITH_PENALTY` with the flag printed on the report. In the reference cohort all eight
penalised arrays inside the sealed set were penalised here and nowhere else.

**At the bench.** Nothing to do for a single warned array. A plate where many arrays warn together is a
scanning or manufacturing pattern worth raising with the core facility.""",

"§17": """**As applied in code.** `step_0_7_call_rate(record, detection_pass_mask, bead_pass_mask)` — the fraction of
probes passing **both** the detection and the bead test.

| quantity | value |
|---|---|
| pass | `CALL_RATE_PASS` = 0.98 |
| borderline | ≥ `CALL_RATE_BORDERLINE` = 0.95 → `CALL_RATE_BORDERLINE` |
| below | `CALL_RATE_FAIL` — hard failure |
| healthy median (n=731) | **0.9983**, p05 0.9961, worst 0.9889 |

Step 0.7b, `step_0_7b_platform_coverage`, is a separate check on a different thing: what fraction of the
chain's **reference CpGs** survived calibration, against `HM450_COVERAGE_MIN` = 0.80. Call rate asks whether
the array worked; coverage asks whether the array carries the loci this instrument reads. An EPIC array can
have an excellent call rate and still fail coverage if the wrong reference is applied — and a 450K array
mis-declared as EPIC fails both, which is the signature of a declaration error rather than a specimen problem.

**At the bench.** Call rate is the compound number a core facility will recognise. If it is borderline while
detection and beads are individually fine, look at which probes are being lost — the two masks disagree only
where one test is marginal.""",

"§18": """**As applied in code.** `step_0_8_sex_check(record, sex_intensities)`, then
`predict_sex(log2_x_median, log2_y_median)`: **F if log2(Y) − log2(X) < −2.0**, else M. Both medians are total
intensities over the manifest's chrX (11,244 probes) and chrY (419 probes), built the same design-aware way as
Step 0.5.

| quantity | value |
|---|---|
| cutoff | `SEX_GETSEX_CUTOFF` = −2.0 |
| agreement with the depositors' published sex | **729 of 731 arrays — 99.73 %** |
| the only disagreements | the two donors whose sex is published as "NA" |
| refusal | `MISMATCH` → hard failure at Step 0.9 |

**This is the strongest single piece of evidence that the QC hand-off decodes what it claims to.** The call
uses no cohort information, no reference panel and no metadata — only chrX and chrY intensities from the array
itself — and it recovers the depositors' own labels on 729 consecutive specimens.

**At the bench.** A mismatch is a sample-tracking alarm before it is anything else: suspect the paperwork, the
plate map, or a swap. Check the declared sex first, because the array is right about 99.7 % of the time. A
donor of unknown sex cannot clear this gate — there is nothing to compare against — and that is a metadata
problem, not an instrument one.""",

"§19": """**As applied in code.** `step_0_9_decision_gate(record, verdict_log_path)` reads the statuses the eight
preceding steps stamped on the record and sorts them into three lists, then decides:

| the gate finds | decision |
|---|---|
| any hard failure | `QUARANTINE` — **the chain stops, nothing is scored, no report is written** |
| no hard failure, one or more borderline flags | `PROCEED_WITH_PENALTY` |
| neither | `PROCEED` |

Hard failures are: any `QUARANTINE_*` status from Steps 0.1–0.3 (this guard was added 2026-09-19 after an
early quarantine fell through to PROCEED); `integrity_status` other than `INTEGRITY_OK`; `ctrl_qc` beginning
`FAIL`; `FAIL_LOW_DETECTION`; `CALL_RATE_FAIL`; coverage `FAIL`; and a sex `MISMATCH`. Borderline: detection
or call rate in their borderline bands, and a bead-count warning. **Deferred** is its own list — a check that
could not be made — and a deferred check is neither a pass nor a failure. `PROVISIONAL_*` statuses land here.

**The caller must stop at the first refusal.** Each step writes its status onto the same record, so a caller
that keeps going overwrites a quarantine with the next step's status: on 2026-09-23 an array-type mismatch
surfaced two gates later as a detection failure for exactly this reason. `run_sample.py` tests for a
`QUARANTINE_*` status after every step and goes straight to this gate.

**A failed decode is a refusal, not a deferral.** If the decoder reaches the files and fails on them, the
sample is `QUARANTINE_CORRUPT_IDAT`. The alternative — catching the exception and letting the QC steps report
`DEFERRED` — is a fail-open: it would calibrate and score a corrupt array with six gates unmeasured. Anything
that converts a failure into a silence is worse than having no gate.

**Measured (732 arrays).** 720 `PROCEED`, 8 `PROCEED_WITH_PENALTY`, 3 `QUARANTINE`, 1 decode error. Every
refusal in the cohort traces to metadata the depositors do not publish, or to one locally truncated file — not
to a specimen the chain misjudged.""",
}


def main():
    s = open(SOP, encoding="utf-8").read()
    # drop any previous generation
    s = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", "", s, flags=re.S)
    lines = s.split("\n")
    out, added = [], 0
    for i, l in enumerate(lines):
        out.append(l)
        m = re.match(r"^#{2,3} (§\d+)\. Step 0\.\d", l)
        if not m or m.group(1) not in DETAIL:
            continue
        out += ["", BEGIN, "", DETAIL[m.group(1)], COMMON, END]
        added += 1
    open(SOP, "w", encoding="utf-8").write("\n".join(out))
    print(f"operational detail written under {added} Stage 0 step sections")
    return added


if __name__ == "__main__":
    main()
