#!/usr/bin/env python3
"""Every folder gets a README that says what it is for and lists what is in it - generated, not written.

Author, 2026-09-25: "can you confirm that each of the README's are accurate now with correct file addresses?"
The honest answer for a hand-written README is only ever "as of when it was typed". So the listings are
generated from the tree, and the purpose lines - the one thing a machine cannot derive - are held in PURPOSE
below and printed as MISSING A PURPOSE if a folder has none.

Each generated README has three parts:
  * what the folder is for (from PURPOSE)
  * what is in it, with each file's description from chain_inventory_v1.json where it has one
  * a marker saying it is generated, so nobody edits it and loses the edit on the next run

A folder that already has a HAND-WRITTEN README is left alone; this only creates and refreshes the ones it
generated itself, marked by the line it writes at the bottom.
"""
import json
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
MP = os.path.dirname(HERE)
MARK = "<!-- generated by kit/build_folder_readmes.py - edit PURPOSE there, not this file -->"

PURPOSE = {
 "chain": ("**The instrument.** Everything a run executes, everything those modules import, the runtime "
           "matrices they read, the test package that proves it works, and the generators that keep the "
           "documents true. If a file is in here, something in a run touches it - and nothing else belongs."),
 "chain/MethylPhys_Interface": ("How a person drives the chain: the single-specimen runner, the report "
                                "builder, and the generators that describe them."),
 "chain/Runtime Matrices": ("The calibrated numbers a reading is corrected by - floors, bands, scale maps, "
                            "the age curve, tier breakpoints. Data, never code."),
 "chain/Runtime Matrices/A_Scoring_Module": ("The identity loci and the per-class floors the gauge divides "
                                             "by, with the band they are read against."),
 "chain/Runtime Matrices/Patient_CMB": ("The sky layer: the CpG-to-pixel mapping and the residual scales "
                                        "each laboratory's plate is drawn on."),
 "chain/TEST_DATA": ("The eleven commissioning arrays and their expected answers. This is the one test that "
                     "proves the chain works end to end; the arrays are named by GSM accession everywhere "
                     "they are used, which is why a filename scan cannot see their readers."),
 "chain/TEST_DATA/idats": ("Raw two-channel intensity files for the eleven commissioning arrays - the input "
                           "the chain is designed to take."),
 "chain/report_builders": ("Pre-atlas report builders, kept because the record cites them. A run does not "
                           "call any of them; the live report is built by MethylPhys_Interface."),
 "chain/example_runs": ("One folder per execution of the chain, with the report it produced. A run makes no "
                        "claim and passes no bar - it is not a test."),
 "chain/tools": ("Fetchers and helpers used to assemble cohorts. Not part of a reading."),
 "kit": ("The gates and generators. Nothing here is part of a reading: these are the programs that check the "
         "chain and keep every derived document true."),
 "kit/results": ("Sealed evidence from the procedures - one file per procedure, named for it. Nothing links "
                 "to a sealed outcome's raw evidence and nothing should have to."),
 "manual": ("The operations manual and everything it is built from. One live version, edited in place; "
            "version control is the history."),
 "manual/report_tab_figures": ("One figure per report tab, generated by kit/build_report_tab_reference.py "
                               "from a finished report. Rendered from each tab's own HTML, not photographed."),
 "sop": ("The chain-of-custody procedure and the generators that keep it current. The procedure is "
         "regenerated, so never edit the markdown by hand."),
 "doors": ("Where a reader starts. Each document here is either a door into the work or a procedure's "
           "pre-registration and sealed outcome."),
 "atlas": ("The reference atlas: the per-cell methylation posterior the composition step reads, with its "
           "provenance and the class mapping."),
 "atlas/iamatlas_class_archives": ("Per-class MCMC archives from the atlas build. Not needed to run a "
                                   "sample; kept so the atlas can be rebuilt."),
 "atlas/healpix_mapping": ("The CpG-to-pixel mapping and the code that generated it - genomically ordered, "
                           "so neighbouring pixels hold neighbouring CpGs."),
 "plates": ("The framework's reference figures. Four of these are embedded in every report by the chain, so "
            "nothing here is decoration to be tidied away without checking which."),
 "papers": ("The papers this work has produced, and the sources they are built from."),
 "hmin_calibration": ("The MCMC calibration behind the class floors, with the reference cells it was fitted "
                      "on and a runner that reproduces every floor in about fifteen seconds."),
 "reference_data": ("The calibrated beta matrices the constants were fitted on, published beside them."),
 "evidence_pre_atlas_2026-04": ("The April 2026 evidence database, published unedited. A DIFFERENT SURFACE "
                                "from the commissioned chain - read its README_FIRST before quoting any "
                                "number from it."),
}


def main():
    root = subprocess.run(["git", "-C", HERE, "rev-parse", "--show-toplevel"],
                          capture_output=True, text=True).stdout.strip()
    rel = os.path.relpath(MP, root)
    tracked = [f for f in subprocess.run(["git", "-C", root, "ls-files"], capture_output=True,
                                         text=True).stdout.split("\n") if f.startswith(rel + "/")]
    inv_p = os.path.join(MP, "chain", "Runtime Matrices", "chain_inventory_v1.json")
    desc = {}
    if os.path.exists(inv_p):
        inv = json.load(open(inv_p, encoding="utf-8"))
        for group in inv.values():
            if isinstance(group, list):
                for e in group:
                    if isinstance(e, dict) and e.get("file"):
                        d_ = e.get("desc") or e.get("description") or e.get("purpose") or ""
                        # role is a classification, not a description: showing it where a
                        # description belongs is how "guard" ended up as the SOP's summary
                        desc[os.path.basename(e["file"])] = str(d_)[:150]
    folders = {}
    for f in tracked:
        folders.setdefault(os.path.dirname(f)[len(rel) + 1:] or ".", []).append(os.path.basename(f))
    made, missing, skipped = 0, [], 0
    for d, files in sorted(folders.items()):
        if len(files) < 4:
            continue
        existing = [x for x in files if x.lower().startswith("readme")]
        target = os.path.join(MP, d, "README.md")
        if existing:
            # refresh only what this script generated; never touch a hand-written README
            try:
                if MARK not in open(os.path.join(MP, d, existing[0]), encoding="utf-8").read():
                    skipped += 1
                    continue
            except OSError:
                skipped += 1
                continue
            target = os.path.join(MP, d, existing[0])
        if d not in PURPOSE:
            missing.append((d, len(files)))
            continue
        L = ["# %s" % d, "", PURPOSE[d], "",
             "## What is in here", "", "| file | |", "|---|---|"]
        for x in sorted(files):
            if x.lower().startswith("readme"):
                continue
            L.append("| [`%s`](%s) | %s |" % (x, x.replace(" ", "%20"), desc.get(x, "")))
        L += ["", "_%d file(s)._ Paths above are relative to this folder, and "
                  "[`kit/link_check.py`](%s/kit/link_check.py) fails the build if any of them stops "
                  "resolving." % (len(files), os.path.relpath(MP, os.path.join(MP, d))), "", MARK, ""]
        open(target, "w", encoding="utf-8").write("\n".join(L))
        made += 1
    print("folder READMEs: %d generated, %d hand-written left alone" % (made, skipped))
    if missing:
        print("  MISSING A PURPOSE (add to PURPOSE in this file):")
        for d, n in missing:
            print("     %-56s %d files" % (d, n))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
