#!/usr/bin/env python3
"""build_repo_inventory.py - doors/REPO_INVENTORY.md, measured from `git ls-files`, never typed.
Weight by folder, file kinds, the generated-documents register (from build_all.GENERATED), and the RETIRED tree."""
import os, subprocess, collections, json, sys, time
K = os.path.dirname(os.path.abspath(__file__)); MP = os.path.dirname(K); ROOT = os.path.dirname(os.path.dirname(MP))
REL = os.path.relpath(MP, ROOT)
sys.path.insert(0, os.path.join(MP, "chain")); import build_all as BA
files = [f for f in subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True).stdout.split("\n") if f.startswith(REL + "/")]
size = {f: (os.path.getsize(os.path.join(ROOT, f)) if os.path.exists(os.path.join(ROOT, f)) else 0) for f in files}
by = collections.defaultdict(lambda: [0, 0])
for f, s in size.items():
    top = f[len(REL) + 1:].split("/")[0]; by[top][0] += 1; by[top][1] += s
kinds = collections.Counter(os.path.splitext(f)[1].lower() or "(none)" for f in files)
retired = [f for f in files if "/RETIRED" in f]
L = [f"# What is in this repository - measured", "",
     f"**GENERATED by `kit/build_repo_inventory.py`** (build_all step 9) from `git ls-files` at {time.strftime('%Y-%m-%d %H:%M')}; {len(files):,} tracked files, "
     f"{sum(size.values())/1e6:.1f} MB under `{REL}/`. Do not edit; rerun `chain/build_all.py`.", "",
     "## Where the weight is", "", "| folder | files | MB |", "|---|---|---|"]
for top, (n, s) in sorted(by.items(), key=lambda kv: -kv[1][1]): L.append(f"| `{top}/` | {n} | {s/1e6:.1f} |")
L += ["", "## File kinds", "", "| kind | files |", "|---|---|"] + [f"| `{k}` | {n} |" for k, n in kinds.most_common(14)]
L += ["", "## Documents that report the chain, and the generator that writes each one", "",
      "Every file below is written from the chain folder by `chain/build_all.py`; a hand edit is overwritten on the next push. "
      "The generated manifest (`../chain/GENERATED_MANIFEST.json`) carries the sha256 of each and of every chain input it was built from.", "",
      "| generated document | written by |", "|---|---|"] + [f"| `../{a}` | `../{b.split(' ')[0]}` |" for a, b in BA.GENERATED]
L += ["", f"## Retired ({len(retired)} files under `RETIRED_*`)", "",
      "Kept as the record of what was built and measured; nothing in the live path reads them. Folders:", ""]
for d in sorted({"/".join(f.split("/")[:f.split("/").index(next(x for x in f.split("/") if x.startswith("RETIRED"))) + 2]) for f in retired}): L.append(f"- `{d[len(REL)+1:]}`")
open(os.path.join(MP, "doors", "REPO_INVENTORY.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
print(f"REPO_INVENTORY.md: {len(files)} files, {len(by)} folders, {len(BA.GENERATED)} generated documents")
