#!/usr/bin/env python3
"""Every folder gets a README that says what it is for and lists what is in it - generated, not written.

Author, 2026-09-25: "can you confirm that each of the README's are accurate now with correct file addresses?"
The honest answer for a hand-written README is only ever "as of when it was typed". So the listings are
generated from the tree, and the purpose lines - the one thing a machine cannot derive - are held in PURPOSE
below and printed as MISSING A PURPOSE if a folder has none.

Each generated README has three parts:
  * what the folder is for (from PURPOSE)
  * what is in it, with each file's description from chain_inventory_v1.json where it has one
  * a marker saying it is generated, so nobody edits it and loses the edit on the next run

A folder that already has a HAND-WRITTEN README is left alone; this only creates and refreshes the ones it
generated itself, marked by the line it writes at the bottom.
"""
import json
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
MP = os.path.dirname(HERE)
MARK = "<!-- generated by kit/build_folder_readmes.py - edit PURPOSE there, not this file -->"

PURPOSE = {
 "chain": ("**The instrument, chain v3.** Everything a v3 run executes, the frozen inputs it reads, the test data that proves it "
           "works end to end, the toolkit stages not yet wired in (TOOLKIT.md), and the generators that keep the documents true."),
 "chain/MethylPhys_Interface": ("How a person drives the chain: the single-specimen runner (run_sample.py) and the v3 report builder."),
 "chain/Runtime Matrices": ("Frozen inputs: the v3 floors, references, composition profiles, noise sites and gates, the IAM-A position, the "
                            "intake thresholds, and the toolkit's panels and sky mapping. Data, never code (two toolkit modules excepted)."),
 "chain/Runtime Matrices/Celltype_Marker": ("Toolkit panels: the NILC marker file (stage 4), the foreign-cell detection panel (stage 3c) and "
                                            "the atlas v2 twin/family thresholds."),
 "chain/Runtime Matrices/Met_A_Floors": ("Chain v3's frozen inputs: the neutrophil Met-A floor and its leave-one-out record, the neutrophil reference, "
                                         "the EPIC blood-composition profiles, and the noise sites and gate. Hashes checked by chain/release_check_v3.py."),
 "chain/Runtime Matrices/Patient_CMB": ("Toolkit, stage 11 (sky map): the CpG-to-pixel mapping, its builder, and the presence floors."),
 "chain/TEST_DATA": ("Bundled test arrays (raw IDAT pairs) the release check runs chain v3 on, end to end."),
 "chain/TEST_DATA/idats": ("Raw two-channel intensity files: four EPIC v1 pairs (read by v3) and seven 450K pairs (refused by v3's platform check)."),
 "chain/tools": ("Fetchers and helpers used to assemble cohorts. Not part of a reading."),
 "kit": ("Repository tools: the link check, folder READMEs, inventory and marked blocks, the Stage 0 intake procedure "
         "(PROC-STAGE0-02) and the release-check entry point. Nothing here is part of a reading."),
 "kit/results": ("Results of the kept procedures (PROC-STAGE0-02) and the last release check."),
 "manual": ("The operations manual for chain v3 and what it is built from."),
 "sop": ("The chain-v3 procedure (MethylPhys_CPG_SOP_v3.md), its full version, and the audits behind it."),
 "doors": ("Where a reader starts, and the development record: each document is a door into the work, a procedure's "
           "pre-registration or sealed outcome, or a development note."),
 "atlas": ("The reference atlases: atlas v2 (current) and the earlier IAMAtlasREBUILD with its provenance and HEALPix mapping."),
 "atlas/iamatlas_class_archives": ("Per-class MCMC archives from the atlas build; the per-CpG brightness posteriors read by the toolkit's "
                                   "stage 11b. Not needed to run a v3 sample."),
 "atlas/healpix_mapping": ("The CpG-to-pixel mapping and the code that generated it - genomically ordered, "
                           "so neighbouring pixels hold neighbouring CpGs."),
 "plates": ("The framework's reference figures."),
 "papers": ("The papers this work has produced, and the sources they are built from."),
 "hmin_calibration": ("The MCMC calibration behind the class floors, with the reference cells it was fitted "
                      "on and a runner that reproduces every floor in about fifteen seconds."),
 "reference_data": ("The calibrated beta matrices the constants were fitted on, published beside them."),
 "evidence_pre_atlas_2026-04": ("The April 2026 evidence database, published unedited. A DIFFERENT SURFACE "
                                "from the commissioned chain - read its README_FIRST before quoting any "
                                "number from it."),
}


def main():
    root = subprocess.run(["git", "-C", HERE, "rev-parse", "--show-toplevel"],
                          capture_output=True, text=True).stdout.strip()
    rel = os.path.relpath(MP, root)
    tracked = [f for f in subprocess.run(["git", "-C", root, "ls-files"], capture_output=True,
                                         text=True).stdout.split("\n") if f.startswith(rel + "/")]
    inv_p = os.path.join(MP, "chain", "Runtime Matrices", "chain_inventory_v1.json")   # retired with chain v2 (2026-10-03): descriptions are empty when absent
    desc = {}
    if os.path.exists(inv_p):
        inv = json.load(open(inv_p, encoding="utf-8"))
        for group in inv.values():
            if isinstance(group, list):
                for e in group:
                    if isinstance(e, dict) and e.get("file"):
                        d_ = e.get("desc") or e.get("description") or e.get("purpose") or ""
                        # role is a classification, not a description: showing it where a
                        # description belongs is how "guard" ended up as the SOP's summary
                        desc[os.path.basename(e["file"])] = str(d_)[:150]
    folders = {}
    for f in tracked:
        folders.setdefault(os.path.dirname(f)[len(rel) + 1:] or ".", []).append(os.path.basename(f))
    made, missing, skipped = 0, [], 0
    for d, files in sorted(folders.items()):
        if len(files) < 4:
            continue
        existing = [x for x in files if x.lower().startswith("readme")]
        target = os.path.join(MP, d, "README.md")
        if existing:
            # refresh only what this script generated; never touch a hand-written README
            try:
                if MARK not in open(os.path.join(MP, d, existing[0]), encoding="utf-8").read():
                    skipped += 1
                    continue
            except OSError:
                skipped += 1
                continue
            target = os.path.join(MP, d, existing[0])
        if d not in PURPOSE:
            missing.append((d, len(files)))
            continue
        L = ["# %s" % d, "", PURPOSE[d], "",
             "## What is in here", "", "| file | |", "|---|---|"]
        for x in sorted(files):
            if x.lower().startswith("readme"):
                continue
            L.append("| [`%s`](%s) | %s |" % (x, x.replace(" ", "%20"), desc.get(x, "")))
        L += ["", "_%d file(s)._ Paths above are relative to this folder, and "
                  "[`kit/link_check.py`](%s/kit/link_check.py) fails the build if any of them stops "
                  "resolving." % (len(files), os.path.relpath(MP, os.path.join(MP, d))), "", MARK, ""]
        open(target, "w", encoding="utf-8").write("\n".join(L))
        made += 1
    print("folder READMEs: %d generated, %d hand-written left alone" % (made, skipped))
    if missing:
        print("  MISSING A PURPOSE (add to PURPOSE in this file):")
        for d, n in missing:
            print("     %-56s %d files" % (d, n))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
