"""switching_order.py — THE SWITCHING ORDER: the chain, one record per stage, everything that touches a stage
clipped to it. This is the master reference. Issue 003 Part II prints from it; build_switching_order_html.py
renders it with copy-paste command blocks. Edit here, nowhere else.

Fields per stage:
  id, name, purpose (one sentence), inputs, outputs, files (repo paths), command (copy-paste, runs from repo root
  with CPG_KIT_DATA set), expected (what a correct run prints/returns), status, lessons (ids + one line each),
  defects (open), procedures (PROC ids that verified this stage), rules (SOP / RUNBOOK sections), do_not.
Status vocabulary: VERIFIED (reproduces from raw public data), BUILT (runs; not independently verified),
KNOWN-DEFECT (runs; output not to be reported), NOT WIRED, TO DO.
"""

SWITCHING_ORDER = [
 dict(id="0", name="Intake", status="BUILT (intensity QCs DEFERRED)",
  purpose="Accept an IDAT pair and a manifest; refuse anything that is not a complete, matched, recognised array.",
  inputs="*_Grn.idat(.gz) + *_Red.idat(.gz); manifest / intake form (age, sex, substrate, sentrix ID if known)",
  outputs="intake record (JSON): array type, integrity hashes, call-rate, quarantine status, decision",
  files=["MethylPhys/chain/stage_0_intake.py","MethylPhys/chain/cpg_intake_form.html"],
  command="cd Biological_Physics && python3 MethylPhys/chain/stage_0_intake.py --grn <GSM>_Grn.idat.gz --red <GSM>_Red.idat.gz --age <yrs> --sex <M|F> --substrate whole_blood",
  expected="decision PASS with array 450K or EPIC; QUARANTINE_INCOMPLETE_MANIFEST if a required field is missing (this must STOP the chain — it once did not).",
  lessons=[("PROC-STAGE0-01","step_0_9 decision gate ignored an early quarantine status (fail-open); closed with a guard 2026-09-19."),
           ("STAGE01_QC","four intensity-dependent QCs (detection-p, bead count, dye bias, control probes) wait on an unwired Stage 1 hand-off - DEFERRED, not skipped.")],
  defects=["intensity QCs deferred until Stage 1 exposes raw intensities"],
  procedures=["PROC-STAGE0-01"], rules=["SOP §100-§103 (Stage 0)","RUNBOOK §4"],
  do_not=["do not let a QUARANTINE status reach Stage 1"]),

 dict(id="1", name="Calibration (IDAT → β)", status="VERIFIED",
  purpose="Turn raw two-colour intensities into per-CpG β on ONE fixed pipeline (methylprep noob, per-sample dye-bias + probe-type normalisation).",
  inputs="IDAT pair from Stage 0", outputs="β vector (416k CpGs on 450K; ~865k on EPIC), float32; pipeline tag 'stage1_noob'",
  files=["MethylPhys/chain/stage_1_idat_calibration.py"],
  command="cd Biological_Physics && python3 -c \"import sys; sys.path.insert(0,'MethylPhys/chain'); from stage_1_idat_calibration import calibrate_idat_to_beta as c; b,m=c('<GSM>_Grn.idat.gz','<GSM>_Red.idat.gz'); b.to_csv('<GSM>_stage1_beta.csv'); print(len(b))\"",
  expected="416,118 CpGs on 450K; against TEST_DATA betas_cache.pkl: r = 1.000000, max |Δβ| = 0 (PROC-CAL-01, 11/11). ~25 s per sample; the 450K manifest downloads once from the methylprep S3 bucket.",
  lessons=[("LESSON-SCALE-01","Stage-1 noob β is +0.066 ABOVE the Roadmap scale on the identity loci. H_min lives on the Roadmap scale. Map before any absolute reading (beta_scale_maps_v1.json). Never re-derive H_min per pipeline."),
           ("PROC-CAL-01","reproduces the project's cached betas exactly on both array types.")],
  defects=[], procedures=["PROC-CAL-01","PHASE 1 (732/732)"], rules=["SOP §109 (β scale)","RUNBOOK §12 (pre-flight: healthy immune β̄ vs 0.737)"],
  do_not=["do not compare a Stage-1 β to an Atlas β, a GEO-processed β, or H_min_beta without the pipeline map"]),

 dict(id="1s", name="Scale map (pipeline → Roadmap)", status="WIRED 2026-09-20 (map PROVISIONAL - Phase 1c pending)",
  purpose="Put the patient's β on the scale H_min and the Atlas were calibrated on, so an ABSOLUTE reading means something. WIRED: Stage 1 stamps meta['pipeline']; cpg_conductor.stage_1s_scale_map applies the map to the gauge path; stage_b_identity emits the identity-loci gauge with scale + reportable labels alongside the wired gauge.",
  inputs="β vector + its pipeline tag", outputs="β on the Roadmap scale; label scale=MAPPED(<pipeline>) or scale=UNMAPPED",
  files=["MethylPhys/chain/Runtime Matrices/A_Scoring_Module/beta_scale_maps_v1.json","MethylPhys/chain/cpg_conductor.py (stage_1s_scale_map, stage_b_identity)","MethylPhys/chain/stage_1_idat_calibration.py (meta['pipeline'])"],
  command="python3 -c \"import json; m=json.load(open('MethylPhys/chain/Runtime Matrices/A_Scoring_Module/beta_scale_maps_v1.json'))['maps']['stage1_noob_450K']; print('beta_roadmap = (beta -', m['intercept'], ') /', m['slope'])\"",
  expected="GSM2333901 (healthy 58M) through run_full: cfg without pipeline → identity immune A 0.8066 BELOW_BAND scale=UNMAPPED reportable=False; with cfg['pipeline']='stage1_noob_450K' → A 0.9748 IN_BAND reportable=True. stage1_noob_450K: slope 1.0127, intercept 0.0662. After mapping, Swedish healthy immune A = 0.990 (p10-p90 0.962-1.016). GEO-processed EPIC and TCGA-sesame entries are TO FIT.",
  lessons=[("LESSON-SCALE-01","three scales measured: Roadmap 0.737 / GEO-processed EPIC 0.774 / Stage-1 0.815 on the same 42k identity loci."),
           ("PHASE 1 addendum","P3 15/15 after the map is a CONSISTENCY check (map fit on the band cohort); Phase 1c tests it on an independent cohort.")],
  defects=["only one pipeline fit; GEO-processed and TCGA maps not yet fit"], procedures=["PHASE 1 addendum"], rules=["SOP §109","RUNBOOK §12"],
  do_not=["do not report a tier from UNMAPPED β"]),

 dict(id="2", name="Deconvolution — Tool A (what is in the tube)", status="VERIFIED",
  purpose="Class composition of the sample from the Atlas (115 cell types → 8 classes), NNLS on the simplex, on Walther's field-ranked class markers.",
  inputs="β on any consistent scale (composition is scale-tolerant; the gauge is not)", outputs="class_fractions (8), celltype fractions (115), residual MAE",
  files=["MethylPhys/chain/Walther_iam_deconvolver/walther_iam_deconvolver.py","MethylPhys/atlas/IAMAtlasREBUILD.csv(.xz)","MethylPhys/atlas/IAMAtlasREBUILD_celltype_to_class.json"],
  command="cd Biological_Physics/MethylPhys/kit && CPG_KIT_DATA=<data dir> python3 PROC_DECON_01.py",
  expected="GSM8772491 (adenoma EPIC) class MAE 0.0004 vs TEST_DATA_MANIFEST; healthy whole blood 83-93% immune, epithelial 0.0000; 648-sample breast anchor r = 1.00000 (PROC-ANCHOR-01).",
  lessons=[("LESSON-DECONV-01","the deconvolver gates no call; composition and gauge stay separable."),
           ("PROC-NILC-01","the Atlas cannot split immune / progenitor / stem_adult in blood (κ 30.6, r +0.99) - Walther's stem_adult share is constraint-chosen. NILC said so in June and was cut for it - and was right: it was rerun and reinstated in September as the class-level second opinion."),
           ("RUNBOOK §11","a check that can be switched off when it trips is not a check.")],
  defects=["blood haematopoietic sub-problem ill-conditioned at field markers (by design report progenitor+stem_adult jointly - Stage 2b)"],
  procedures=["PROC-DECON-01","PROC-ANCHOR-01","PROC-PLASMA-MIX-01","PROC-N7-01 (R1 pass)"], rules=["SOP §10-§12","§108 reporting rule"],
  do_not=["do not use the cell-type marker pool as a deconvolution basis (that was NILC's failure mode)"]),

 dict(id="2b", name="Lineage split — Tool B (how a compartment divides)", status="BUILT",
  purpose="Split ONE compartment Tool A found (default haematopoietic = progenitor + stem_adult) using only the CpGs where the members differ; refuse when the split is undetermined.",
  inputs="Tool A class fractions + β", outputs="SPLIT (fractions, κ) or COMPARTMENT_ONLY (reason)",
  files=["MethylPhys/chain/Lineage_Splitter/lineage_splitter.py"],
  command="cd Biological_Physics/MethylPhys/kit && CPG_KIT_DATA=<data dir> python3 PROC_SEP_03.py",
  expected="7/7 whole blood SPLIT, κ 3.9-5.2, stem_adult = 0.000; tissue without haematopoietic mass → COMPARTMENT_ONLY (κ = ∞).",
  lessons=[("PROC-SEP-01","the Atlas holds 1,290 CpGs that separate HSC from progenitor by >0.2β; the single solve used ~129 of them."),
           ("PROC-SEP-02","adding contrast markers to Tool A moved κ 30.6→17 but never converged the two solvers: the split is not data-determined inside one solve."),
           ("PROC-SEP-03","on the contrast vocabulary alone κ ≈ 5 and the split is clean - 'knowing what you're good at and letting someone else be good at the rest'.")],
  defects=[], procedures=["PROC-SEP-03"], rules=["§108"], do_not=["do not report stem_adult separately on blood - the resolved share is zero"]),

 dict(id="3", name="Foreground subtraction (age / sex / smoking)", status="NOT WIRED by decision",
  purpose="Remove known non-disease axes before the gauge - built as test-only foregrounds; the age band (Stage B) carries age instead.",
  inputs="β", outputs="-", files=["RETIRED/… Age_Sex_Smoker Axis Foreground (test-only)"],
  command="(none - not in the chain)", expected="-",
  lessons=[("SOP §104","decision: age handled by the age-matched band, not by subtraction; sex and smoking remain nulls (N-sex) not corrections.")],
  defects=[], procedures=[], rules=["SOP §104"], do_not=["do not silently add a foreground correction - it changes what 'healthy range' means"]),

 dict(id="B", name="Class gauge  A = H(β̄)/H_min on IDENTITY loci, read against the age band", status="KNOWN-DEFECT as wired; correct statistic has a PROVISIONAL band",
  purpose="The call. For each class present (§108), the binary entropy of the mean β over that class's identity loci, divided by the MCMC floor, placed in the age-decade percentile band.",
  inputs="β on the Roadmap scale (Stage 1s); class fractions (Stage 2); age", outputs="per class: A, placement (BELOW/IN/ABOVE band), tier input; gauge_surface label",
  files=["MethylPhys/chain/cpg_conductor.py (stage_b_classes)","MethylPhys/chain/cpg_gauge_engine.py","MethylPhys/chain/Runtime Matrices/A_Scoring_Module/iamatlas_gauge_identity_loci_v1_0.json","…/age_reference_matrix.json","Record/VAL_PostAtlas/CPG_PHASE1_identity_band_GSE87571/identity_band_v1.json"],
  command="cd Biological_Physics/MethylPhys/kit && CPG_KIT_DATA=<data dir> python3 PROC_FORMULA_01.py",
  expected="Immune H_min 0.838889 (Roadmap scale, A=1 at β̄ 0.7318). Healthy Stage-1 blood after the scale map: A ≈ 0.99, in band. Synthetic healthy (Atlas posterior): A 0.984, in band. UNMAPPED Stage-1 blood reads 0.82 - that is the scale, not disease.",
  lessons=[("PROC-N7-01","as wired, the conductor reads the MARKER UNION (bimodal, ~3k CpGs) not the identity loci; age_reference_matrix was compiled the same way, so real blood agreed with itself for eleven weeks. Caught by the synthetic patient in one run."),
           ("PROC-FORMULA-01 / RULING A3","two statistics, two surfaces: mean-of-H over discriminative markers = SEPARATION; H(β̄) over identity loci = GAUGE. Each reproduces its own seal; neither is 'the regression'."),
           ("LESSON-SCALE-01","the gauge input must be on the floor's scale."),
           ("PROC-CHAIN-01","stem_adult false BREACH in 6/7 healthy blood from an n=28 band → §108 reporting rule."),
           ("Floor / ruler / band","FLOOR = H_min (physics, 40 values). RULER = the identity loci. BAND = a cohort percentile with its own provenance. Every 'healthy reads wrong' case traced to a band or a scale, never a floor.")],
  defects=["conductor still wired to the marker union (labelled gauge_surface='marker_union'); switch only when identity_band_v1 is confirmed on an independent cohort (Phase 1c)","band is one population (N. Sweden) - Phase 1b","N-sex indicates sex-split bands 35-64","N-plate not yet run"],
  procedures=["PROC-FORMULA-01","PROC-N7-01","PHASE 1"], rules=["SOP §41-§43, §105-§109","RUNBOOK §10-§12","§108 reporting rule"],
  do_not=["do not compute Cohen's d between groups and call it a result - the physics measures, cohorts only point","do not read A from marker-union β","do not read A from UNMAPPED β"]),

 dict(id="4.5", name="Bidirectional decomposition", status="BUILT (wired 2026-06-27)",
  purpose="H(β̄) is symmetric about 0.5: a disease pushing some CpGs up and others down can leave β̄ unmoved. Stage 4.5 scores the signed, weighted departure on directional panels so that case is not missed.",
  inputs="β; directional_panels_v1_0.json", outputs="signed composite z per panel",
  files=["MethylPhys/chain/Runtime Matrices/Directional Panel/bidirectional_decomposition.py","…/directional_panels_v1_0.json"],
  command="(runs inside cpg_conductor.run_full)", expected="VAL-050 pooled d=+0.077 → VAL-051 directional d=+0.624 on the same AIBL AD samples.",
  lessons=[("CCL-001","the directional-score principle."),("first-review objection","the entropy-folding objection has a runtime answer: this stage.")],
  defects=[], procedures=[], rules=["SOP §44"], do_not=["do not report a null from the gauge alone on a class whose directional panel fired"]),

 dict(id="4.6", name="Patient CMB (brilliance map)", status="BUILT (2026-06-29)",
  purpose="Per-class z-departure of the patient's β from the Atlas posterior (mean, sd) on the HEALPix NSIDE=128 grid - the cosmology borrow that shows WHERE on the genome the departure sits.",
  inputs="β; Atlas *_mean/*_sd columns; cpg→pixel mapping", outputs="per-class median |z|, assessable flag, Mollweide plate",
  files=["MethylPhys/chain/cpg_patient_cmb.py","MethylPhys/chain/Runtime Matrices/cpg healpix mapping/iamatlas_cpg_to_healpix_nside128.npy","MethylPhys/plates/CPG_Plate_05_Four_Skies_Issue003.png"],
  command="(see Issue 003 §5A.4; requires healpy)", expected="healthy blood: uniform tint = the documented reference offset; the 'assessable' flag wrongly admits classes the deconvolver says are absent (known).",
  lessons=[("§1.6 ledger","component separation, end-to-end simulation and cross-method disagreement - the CMB disciplines that found what cohorts could not."),("Plate 05","four skies on one grid: Planck realisation, Atlas immune posterior, a real patient, the z-map.")],
  defects=["assessability should be gated by Stage 2 presence, not by median |z|"], procedures=[], rules=[], do_not=["do not read the uniform tint as disease - it is the scale offset made visible"]),

 dict(id="5", name="Second chain — Mahalanobis departure", status="BUILT (KNOWN-DEFECT input)",
  purpose="Multivariate distance of the per-cell separation vector from the age-matched healthy reference hull.",
  inputs="per-cell A (separation surface); mahalanobis_healthy_reference_v2_0", outputs="distance, beyond-band flag, driver class",
  files=["MethylPhys/chain/stage_5_second_chain.py","MethylPhys/chain/Runtime Matrices/Mahalanobis_healthy_reference/*","…/iamatlas_mahalanobis_scoring.py"],
  command="(runs inside cpg_conductor.run_full)", expected="on the 11 test samples the distance was driven entirely by the stem_adult false alarm - not reportable until Stage B is fixed.",
  lessons=[("PROC-CHAIN-01 defect 2","run_full emits {distance, beyond, driver}; the report builder reads mahalanobis_distance - a naming inconsistency, not a live bug (the report is fed by a different bundle)."),("first review","a 'direction' claim from Mahalanobis distances is a dispersion difference; test it as one.")],
  defects=["input inherits Stage B defects","key naming inconsistency"], procedures=["PROC-CHAIN-01"], rules=["SOP §60-§63"], do_not=["do not report Stage 5 until Stage B is switched to the identity-loci gauge"]),

 dict(id="6", name="Cellular age", status="KNOWN-DEFECT (not reportable)",
  purpose="Invert the age trajectory of A to an inferred cellular age per class.",
  inputs="per-class A; age_reference_matrix", outputs="cellular age per class",
  files=["MethylPhys/chain/Runtime Matrices/Cellular_Age/iam_cellular_age_scoring.py"],
  command="(runs inside cpg_conductor.run_full)", expected="on the 11 test samples: 4.0 years for adults on five of six classes - pinned at the curve floor.",
  lessons=[("PROC-CHAIN-01 defect 3","module existed only in the user's trial bundle until 2026-09-19; the repo chain could not run without it."),("VAL-020","the physics-inversion age result is r = -0.184 with honest error bars; the r = 0.9999 figure was a regression-trained predictor and is not claimed.")],
  defects=["curve floor; needs the identity-loci band (Phase 1) before recalibration"], procedures=["PROC-CHAIN-01"], rules=[], do_not=["do not print a cellular age on a report"]),

 dict(id="7", name="Tier", status="BUILT",
  purpose="Map placement to one of six engine tiers; per-class ceiling A_max = 1/H_min caps what is reachable (stem_pluri is structurally blind to BREACH on methylation).",
  inputs="A, placement, class", outputs="tier; BORDERLINE_TIER flag",
  files=["MethylPhys/chain/Runtime Matrices/Tier_breakpoints/tier_breakpoints.json"],
  command="(runs inside cpg_conductor.run_full)", expected="SUPPRESSED / NORMAL / ELEVATED / WARBURG_TRANSITION / SIGNIFICANTLY_ELEVATED / BREACH; edge 1.04→1.01 (2026-07-03).",
  lessons=[("saturation","five substrates, forty floors, forty ceilings; a class saturated on one substrate is read on another (A_active)."),("CHAIN_RULES","all 1,174 EPIC-Italy patients saturate on ≥1 class; only cycling in range for ~50%.")],
  defects=[], procedures=[], rules=["SOP §70-§72"], do_not=["do not report a tier for a class that fails §108"]),

 dict(id="8", name="Disease matching (separation surface)", status="BUILT",
  purpose="Directional concordance of the per-cell separation vector with the disease matrix (v1.13, 81 rows, 49 VAL-anchored). Indicative tier only.",
  inputs="per-cell A (mean-of-H over discriminative markers); disease matrix; origin cells", outputs="ranked disease concordance, INDICATIVE",
  files=["MethylPhys/chain/Disease Matrix/disease_cell_signature_matrix_v1_13.csv","…/disease_origin_cells.json"],
  command="(runs inside cpg_conductor.run_full)", expected="direction read exactly as the matrix writes it; the MDS row (HSC up, GMP down) is the test that the §108 merge is gauge-only.",
  lessons=[("CCL-019/020","score direction depends on (class, compartment), not disease alone; specimen × class × panel are three independent dimensions."),("CCL-039","marker-tile and full-genome A are two observables that move in opposite directions in tumour vs adjacent normal."),("origin gate","loads disease_origin_cells inside a bare except → fails OPEN (patient-safety finding, first read).")],
  defects=["origin-gate fail-open (flagged; verify closed)"], procedures=["PROC-ANCHOR-01 (surface reproduces)"], rules=["SOP §80-§85","§105"], do_not=["do not use this surface for the gauge (bimodal → Jensen inflation)"]),

 dict(id="9", name="Report", status="BUILT",
  purpose="The patient-facing document: composition, per-class gauge with band placement (only §108 classes), disease concordance (indicative), legal gate against a CANNOT_SAY list.",
  inputs="everything above", outputs="PDF / HTML report", files=["MethylPhys/chain/cpg_report_builder.py","MethylPhys/chain/cpg_gauge.py","MethylPhys/chain/report_builders/*"],
  command="(see cpg_report_builder.py --help)", expected="every number carries its surface and scale label; the 'draft report scanned against a CANNOT_SAY list' wording is the legal gate's own vocabulary.",
  lessons=[("first read","two stale docstrings described the retired method, one printing on the patient figure - fixed."),("language discipline","flag-and-refer, research stage; nothing here is clinical validation.")],
  defects=[], procedures=[], rules=["SOP §90-§96"], do_not=["do not print an UNMAPPED A, a stem_adult gauge on blood, a Stage 5 distance, or a cellular age"]),

 dict(id="N", name="Nulls and simulation (run on EVERY release)", status="VERIFIED",
  purpose="The relays. Synthetic patients with known truth through the whole chain (N7); cross-method deconvolution disagreement as a diagnostic; random-panel, split-half, sex, plate nulls.",
  inputs="the chain at HEAD", outputs="pass/fail per null; a ledger row on every disagreement",
  files=["MethylPhys/chain/Synthetic_Patient_Generator/synthetic_patient_generator.py","MethylPhys/chain/CPG_Null_Runner/cpg_null_runner.py","Record/VAL_PostAtlas/CPG_PHASE1_identity_band_GSE87571/phase1_run.py"],
  command="cd Biological_Physics/MethylPhys/chain && python3 -c \"import sys; sys.path.insert(0,'Synthetic_Patient_Generator'); import synthetic_patient_generator as S; c=S.SyntheticCohort(n_case=0,n_hc=16,random_seed=20260919,composition_alpha=S.WHOLE_BLOOD_ALPHA); c.generate(); print(c.beta_matrix.shape)\"",
  expected="N7: composition recovered on every class; synthetic healthy IN band on the identity-loci gauge after the scale map (15/15), NOT in band on a random panel (0/16).",
  lessons=[("RUNBOOK §11","Trust your equipment. Two relays (NILC, the synthetic generator) tripped on the same fault from two directions and were both reset without a fault-finding."),("§1.6","every time a cosmology tool finds what a cohort could not, it gets a row the same day.")],
  defects=["N-plate not yet run on any cohort"], procedures=["PROC-N7-01","PROC-NILC-01","PHASE 1"], rules=["RUNBOOK §10-§12"],
  do_not=["do not disable a check because it disagrees"]),
]

def stage(id_): return next(s for s in SWITCHING_ORDER if s["id"] == str(id_))
