#!/usr/bin/env python3
"""build_manual_v3.py - the operations manual for chain v3, as a PDF, generated from the documents that hold its content.

    python3 build_manual_v3.py [out.pdf]        default: MethylPhys_CPG_Operations_Manual.pdf beside this file

Content, in order, each read from its file at build time (nothing typed here):
  1. OM_v3_neutrophil_chain.md        the operator chapter: before a run, the run, reading the report, faults
  2. ../doors/CHAIN_SEQUENCE.md       the live path as the code runs it (generated by chain/build_chain_sequence.py)
  3. ../chain/TOOLKIT.md              the toolkit stages, not yet wired into v3
The procedure itself is ../sop/MethylPhys_CPG_SOP_v3.md. Exit 1 if a source is missing or the PDF is not written.
Needs reportlab (requirements: the chain environment).
"""
import os, re, sys, html, hashlib, datetime

HERE = os.path.dirname(os.path.abspath(__file__)); MP = os.path.dirname(HERE)
SOURCES = [("Operations - chain v3, neutrophils", os.path.join(HERE, "OM_v3_neutrophil_chain.md")),
           ("The chain, step by step", os.path.join(MP, "doors", "CHAIN_SEQUENCE.md")),
           ("The toolkit", os.path.join(MP, "chain", "TOOLKIT.md"))]


def inline(t):
    t = html.escape(t, quote=False)
    t = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\1", t)
    t = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", t)
    t = re.sub(r"(?<![\w*])\*(?!\s)(.+?)(?<!\s)\*(?![\w*])", r"<i>\1</i>", t)
    t = re.sub(r"`([^`]+)`", r'<font face="Courier">\1</font>', t)
    return t


def flow(md, S):
    from reportlab.platypus import Paragraph, Spacer, Table, TableStyle, Preformatted
    from reportlab.lib import colors
    out, lines, i = [], md.splitlines(), 0
    while i < len(lines):
        l = lines[i]
        if l.startswith("```"):
            j = i + 1
            while j < len(lines) and not lines[j].startswith("```"): j += 1
            out.append(Preformatted("\n".join(lines[i + 1:j]), S["code"])); i = j + 1; continue
        if l.startswith("|"):
            rows = []
            while i < len(lines) and lines[i].startswith("|"):
                cells = [c.strip() for c in lines[i].strip().strip("|").split("|")]
                if not all(re.fullmatch(r":?-{2,}:?", c) for c in cells if c): rows.append(cells)
                i += 1
            n = max(len(r) for r in rows); rows = [r + [""] * (n - len(r)) for r in rows]
            data = [[Paragraph(inline(c), S["cell"]) for c in r] for r in rows]
            t = Table(data, repeatRows=1, colWidths=[S["width"] / n] * n)
            t.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.3, colors.grey), ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8eef4")),
                                   ("VALIGN", (0, 0), (-1, -1), "TOP")]))
            out += [t, Spacer(1, 6)]; continue
        m = re.match(r"(#{1,4})\s+(.*)", l)
        if m:
            out.append(Paragraph(inline(m.group(2)), S["h%d" % min(len(m.group(1)) + 1, 4)])); i += 1; continue
        if re.match(r"\s*([-*]|\d+\.)\s+", l):
            out.append(Paragraph(inline(re.sub(r"^\s*([-*]|\d+\.)\s+", "", l)), S["bullet"], bulletText="-" if re.match(r"\s*[-*]", l) else re.match(r"\s*(\d+\.)", l).group(1)))
            i += 1; continue
        if not l.strip(): i += 1; continue
        para = [l]
        i += 1
        while i < len(lines) and lines[i].strip() and not re.match(r"(#|\||```|\s*([-*]|\d+\.)\s)", lines[i]):
            para.append(lines[i]); i += 1
        out.append(Paragraph(inline(" ".join(para)), S["body"]))
    return out


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "MethylPhys_CPG_Operations_Manual.pdf")
    if not os.path.isabs(out): out = os.path.join(os.getcwd(), out)
    missing = [p for _, p in SOURCES if not os.path.exists(p)]
    if missing: print("build_manual_v3: missing source(s):", missing); sys.exit(1)
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
    ss = getSampleStyleSheet(); W = letter[0] - 1.5 * inch
    S = {"h1": ss["Title"], "h2": ss["Heading1"], "h3": ss["Heading2"], "h4": ss["Heading3"],
         "body": ParagraphStyle("b", parent=ss["BodyText"], fontSize=9.5, leading=12.5),
         "bullet": ParagraphStyle("u", parent=ss["BodyText"], fontSize=9.5, leading=12.5, leftIndent=14, bulletIndent=4),
         "cell": ParagraphStyle("c", parent=ss["BodyText"], fontSize=7.2, leading=8.8),
         "code": ParagraphStyle("k", parent=ss["Code"], fontSize=7.5, leading=9), "width": W}
    stamp = datetime.date.today().isoformat()
    story = [Paragraph("MethylPhys CPG - Operations Manual, chain v3", S["h1"]),
             Paragraph("Development build, not commissioned; not a diagnostic test. Generated %s by manual/build_manual_v3.py from the files "
                       "named at the start of each part. The procedure is sop/MethylPhys_CPG_SOP_v3.md." % stamp, S["body"]), Spacer(1, 10)]
    hashes = []
    for k, (title, path) in enumerate(SOURCES):
        md = open(path, encoding="utf-8").read(); hashes.append((os.path.relpath(path, MP), hashlib.sha256(md.encode()).hexdigest()[:12]))
        if k: story.append(PageBreak())
        story.append(Paragraph("Part %d. %s" % (k + 1, html.escape(title)), S["h2"]))
        story.append(Paragraph("Source: <font face='Courier'>%s</font>" % html.escape(os.path.relpath(path, MP)), S["body"]))
        story += flow(md, S)
    story += [PageBreak(), Paragraph("Sources", S["h2"])] + [Paragraph("<font face='Courier'>%s</font>  sha256 %s" % (html.escape(a), b), S["body"]) for a, b in hashes]
    SimpleDocTemplate(out, pagesize=letter, leftMargin=0.75 * inch, rightMargin=0.75 * inch, topMargin=0.7 * inch, bottomMargin=0.7 * inch,
                      title="MethylPhys CPG Operations Manual - chain v3").build(story)
    ok = os.path.exists(out) and os.path.getsize(out) > 2000
    print("manual: %s (%d bytes)%s" % (out, os.path.getsize(out) if os.path.exists(out) else 0, "" if ok else " - NOT WRITTEN"))
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
